export const cityOptionsMap = {
  Australia: [
    { label: { en: "Sydney, NSW", zh: "悉尼, 新南威尔士州" }, value: "Sydney, NSW" },
    { label: { en: "Melbourne, VIC", zh: "墨尔本, 维多利亚州" }, value: "Melbourne, VIC" },
    { label: { en: "Brisbane, QLD", zh: "布里斯班, 昆士兰州" }, value: "Brisbane, QLD" },
    { label: { en: "Perth, WA", zh: "珀斯, 西澳大利亚州" }, value: "Perth, WA" },
    { label: { en: "Canberra, ACT", zh: "堪培拉, 首都领地" }, value: "Canberra, ACT" },
    { label: { en: "Adelaide, SA", zh: "阿德莱德, 南澳大利亚州" }, value: "Adelaide, SA" },
    { label: { en: "Albany, WA", zh: "奥尔巴尼, 西澳大利亚州" }, value: "Albany, WA" },
    { label: { en: "Albury, NSW", zh: "奥尔伯里, 新南威尔士州" }, value: "Albury, NSW" },
    { label: { en: "Ballarat, VIC", zh: "巴拉瑞特, 维多利亚州" }, value: "Ballarat, VIC" },
    { label: { en: "Banyo, QLD", zh: "Banyo, 昆士兰州" }, value: "Banyo, QLD" },
    { label: { en: "Bathurst, NSW", zh: "巴瑟斯特, 新南威尔士州" }, value: "Bathurst, NSW" },
    { label: { en: "Bendigo, VIC", zh: "本迪戈, 维多利亚州" }, value: "Bendigo, VIC" },
    { label: { en: "Bunbury, WA", zh: "班伯里, 西澳大利亚州" }, value: "Bunbury, WA" },
    { label: { en: "Bundaberg, QLD", zh: "班达伯格, 昆士兰州" }, value: "Bundaberg, QLD" },
    { label: { en: "Cairns, QLD", zh: "凯恩斯, 昆士兰州" }, value: "Cairns, QLD" },
    { label: { en: "Camperdown, VIC", zh: "Camperdown, 维多利亚州" }, value: "Camperdown, VIC" },
    { label: { en: "Coffs Harbour, NSW", zh: "科夫斯港, 新南威尔士州" }, value: "Coffs Harbour, NSW" },
    { label: { en: "Dandenong, VIC", zh: "Dandenong, 维多利亚州" }, value: "Dandenong, VIC" },
    { label: { en: "Darwin, NT", zh: "达尔文, 北领地" }, value: "Darwin, NT" },
    { label: { en: "Dubbo, NSW", zh: "达博, 新南威尔士州" }, value: "Dubbo, NSW" },
    { label: { en: "Edinburgh, SA", zh: "爱丁堡, 南澳大利亚州" }, value: "Edinburgh, SA" },
    { label: { en: "Footscray, VIC", zh: "Footscray, 维多利亚州" }, value: "Footscray, VIC" },
    { label: { en: "Fortitude Valley, QLD", zh: "Fortitude Valley, 昆士兰州" }, value: "Fortitude Valley, QLD" },
    { label: { en: "Geelong, VIC", zh: "吉朗, 维多利亚州" }, value: "Geelong, VIC" },
    { label: { en: "Geraldton, WA", zh: "杰拉尔顿, 西澳大利亚州" }, value: "Geraldton, WA" },
    { label: { en: "Gold Coast, QLD", zh: "黄金海岸, 昆士兰州" }, value: "Gold Coast, QLD" },
    { label: { en: "Heidelberg, VIC", zh: "Heidelberg, 维多利亚州" }, value: "Heidelberg, VIC" },
    { label: { en: "Hervey Bay, QLD", zh: "赫维湾, 昆士兰州" }, value: "Hervey Bay, QLD" },
    { label: { en: "Hobart, TAS", zh: "霍巴特, 塔斯马尼亚州" }, value: "Hobart, TAS" },
    { label: { en: "Hoppers Crossing, VIC", zh: "Hoppers Crossing, 维多利亚州" }, value: "Hoppers Crossing, VIC" },
    { label: { en: "Kalgoorlie, WA", zh: "卡尔古利, 西澳大利亚州" }, value: "Kalgoorlie, WA" },
    { label: { en: "Keswick, SA", zh: "凯西克, 南澳大利亚州" }, value: "Keswick, SA" },
    { label: { en: "Larrakeyah, NT", zh: "拉腊基亚, 北领地" }, value: "Larrakeyah, NT" },
    { label: { en: "Launceston, TAS", zh: "朗塞斯顿, 塔斯马尼亚州" }, value: "Launceston, TAS" },
    { label: { en: "Mackay, QLD", zh: "麦凯, 昆士兰州" }, value: "Mackay, QLD" },
    { label: { en: "Mildura, VIC", zh: "米尔杜拉, 维多利亚州" }, value: "Mildura, VIC" },
    { label: { en: "Mount Gambier, SA", zh: "甘比尔山, 南澳大利亚州" }, value: "Mount Gambier, SA" },
    { label: { en: "Newcastle, NSW", zh: "纽卡斯尔, 新南威尔士州" }, value: "Newcastle, NSW" },
    { label: { en: "North Ryde, NSW", zh: "North Ryde, 新南威尔士州" }, value: "North Ryde, NSW" },
    { label: { en: "North Sydney, NSW", zh: "North Sydney, 新南威尔士州" }, value: "North Sydney, NSW" },
    { label: { en: "Nowra, NSW", zh: "瑙拉, 新南威尔士州" }, value: "Nowra, NSW" },
    { label: { en: "Orange, NSW", zh: "奥兰治, 新南威尔士州" }, value: "Orange, NSW" },
    { label: { en: "Parkville, VIC", zh: "Parkville, 维多利亚州" }, value: "Parkville, VIC" },
    { label: { en: "Parramatta, NSW", zh: "Parramatta, 新南威尔士州" }, value: "Parramatta, NSW" },
    { label: { en: "Port Macquarie, NSW", zh: "麦夸里港, 新南威尔士州" }, value: "Port Macquarie, NSW" },
    { label: { en: "Robertson Barracks, NT", zh: "Robertson Barracks, 北领地" }, value: "Robertson Barracks, NT" },
    { label: { en: "Robertson, NT", zh: "罗伯逊, 北领地" }, value: "Robertson, NT" },
    { label: { en: "Rockdale, NSW", zh: "Rockdale, 新南威尔士州" }, value: "Rockdale, NSW" },
    { label: { en: "Rockhampton, QLD", zh: "罗克汉普顿, 昆士兰州" }, value: "Rockhampton, QLD" },
    { label: { en: "Shepparton, VIC", zh: "谢珀顿, 维多利亚州" }, value: "Shepparton, VIC" },
    { label: { en: "St Lucia, NSW", zh: "St Lucia, 新南威尔士州" }, value: "St Lucia, NSW" },
    { label: { en: "Sunshine Coast, QLD", zh: "阳光海岸, 昆士兰州" }, value: "Sunshine Coast, QLD" },
    { label: { en: "Tamworth, NSW", zh: "塔姆沃思, 新南威尔士州" }, value: "Tamworth, NSW" },
    { label: { en: "Tindal, NT", zh: "廷达尔, 北领地" }, value: "Tindal, NT" },
    { label: { en: "Toowoomba, QLD", zh: "图文巴, 昆士兰州" }, value: "Toowoomba, QLD" },
    { label: { en: "Townsville, QLD", zh: "汤斯维尔, 昆士兰州" }, value: "Townsville, QLD" },
    { label: { en: "Wagga Wagga, NSW", zh: "瓦加瓦加, 新南威尔士州" }, value: "Wagga Wagga, NSW" },
    { label: { en: "Warrnambool, VIC", zh: "沃南布尔, 维多利亚州" }, value: "Warrnambool, VIC" },
    { label: { en: "Werribee, VIC", zh: "韦里比, 维多利亚州" }, value: "Werribee, VIC" },
    { label: { en: "Wollongong, NSW", zh: "卧龙岗, 新南威尔士州" }, value: "Wollongong, NSW" },
    { label: { en: "Woomera, SA", zh: "伍默拉, 南澳大利亚州" }, value: "Woomera, SA" },
    { label: { en: "York, WA", zh: "约克, 西澳大利亚州" }, value: "York, WA" },
    { label: { en: "South Australia, SA", zh: "南澳大利亚, 南澳大利亚州" }, value: "South Australia, SA" },
    { label: { en: "Northern Territory, NT", zh: "北领地, 北领地" }, value: "Northern Territory, NT" },
    { label: { en: "Ayr, QLD", zh: "艾尔, 昆士兰州" }, value: "Ayr, QLD" }
  ],
  China: [
    { label: { en: "Beijing", zh: "北京" }, value: "Beijing" },
    { label: { en: "Shanghai", zh: "上海" }, value: "Shanghai" },
    { label: { en: "Shenzhen", zh: "深圳" }, value: "Shenzhen" },
    { label: { en: "Guangzhou", zh: "广州" }, value: "Guangzhou" },
    { label: { en: "Chengdu", zh: "成都" }, value: "Chengdu" },
    { label: { en: "Hangzhou", zh: "杭州" }, value: "Hangzhou" },
    { label: { en: "Nanjing", zh: "南京" }, value: "Nanjing" },
    { label: { en: "Suzhou", zh: "苏州" }, value: "Suzhou" },
    { label: { en: "Wuhan", zh: "武汉" }, value: "Wuhan" },
    { label: { en: "Xiamen", zh: "厦门" }, value: "Xiamen" }
  ],
  "Hong Kong": [
    { label: { en: "Central", zh: "中环" }, value: "Central" },
    { label: { en: "Causeway Bay", zh: "铜锣湾" }, value: "Causeway Bay" },
    { label: { en: "Tsim Sha Tsui", zh: "尖沙咀" }, value: "Tsim Sha Tsui" },
    { label: { en: "Kwun Tong", zh: "观塘" }, value: "Kwun Tong" },
    { label: { en: "Mong Kok", zh: "旺角" }, value: "Mong Kok" },
    { label: { en: "North Point", zh: "北角" }, value: "North Point" },
    { label: { en: "Quarry Bay", zh: "鲗鱼涌" }, value: "Quarry Bay" },
    { label: { en: "Tai Po", zh: "大埔" }, value: "Tai Po" },
    { label: { en: "Tuen Mun", zh: "屯门" }, value: "Tuen Mun" },
    { label: { en: "Wan Chai", zh: "湾仔" }, value: "Wan Chai" }
  ],
  "Singapore": [
    { label: { en: "Central Region", zh: "中央区" }, value: "Central Region" },
    { label: { en: "Orchard", zh: "乌节路" }, value: "Orchard" },
    { label: { en: "Raffles Place", zh: "莱佛士坊" }, value: "Raffles Place" },
    { label: { en: "Marina Bay", zh: "滨海湾" }, value: "Marina Bay" },
    { label: { en: "Jurong East", zh: "裕廊东" }, value: "Jurong East" },
    { label: { en: "Punggol", zh: "榜鹅" }, value: "Punggol" },
    { label: { en: "Sengkang", zh: "盛港" }, value: "Sengkang" },
    { label: { en: "Sentosa", zh: "圣淘沙" }, value: "Sentosa" },
    { label: { en: "Tampines", zh: "淡滨尼" }, value: "Tampines" },
    { label: { en: "Woodlands", zh: "兀兰" }, value: "Woodlands" }
  ],
  "Taiwan": [
    { label: { en: "Taipei", zh: "台北" }, value: "Taipei" },
    { label: { en: "New Taipei", zh: "新北" }, value: "New Taipei" },
    { label: { en: "Taichung", zh: "台中" }, value: "Taichung" },
    { label: { en: "Kaohsiung", zh: "高雄" }, value: "Kaohsiung" },
    { label: { en: "Chiayi", zh: "嘉义" }, value: "Chiayi" },
    { label: { en: "Hsinchu", zh: "新竹" }, value: "Hsinchu" },
    { label: { en: "Hualien", zh: "花莲" }, value: "Hualien" },
    { label: { en: "Keelung", zh: "基隆" }, value: "Keelung" },
    { label: { en: "Tainan", zh: "台南" }, value: "Tainan" },
    { label: { en: "Taoyuan", zh: "桃园" }, value: "Taoyuan" }
  ],
      "United Kingdom": [
    { label: { en: "London", zh: "伦敦" }, value: "London" },
    { label: { en: "Manchester", zh: "曼彻斯特" }, value: "Manchester" },
    { label: { en: "Birmingham", zh: "伯明翰" }, value: "Birmingham" },
    { label: { en: "Edinburgh", zh: "爱丁堡" }, value: "Edinburgh" },
    { label: { en: "Glasgow", zh: "格拉斯哥" }, value: "Glasgow" },
    { label: { en: "Bristol", zh: "布里斯托" }, value: "Bristol" },
    { label: { en: "Leeds", zh: "利兹" }, value: "Leeds" }
  ],
  "France": [
    { label: { en: "Paris", zh: "巴黎" }, value: "Paris" },
    { label: { en: "Lyon", zh: "Lyon" }, value: "Lyon" },
    { label: { en: "Toulouse", zh: "Toulouse" }, value: "Toulouse" },
    { label: { en: "La Defense", zh: "La Defense" }, value: "La Defense" }
  ],
  "Italy": [
    { label: { en: "Rome", zh: "Rome" }, value: "Rome" },
    { label: { en: "Milan", zh: "Milan" }, value: "Milan" },
    { label: { en: "Milano", zh: "Milano" }, value: "Milano" },
    { label: { en: "Roma", zh: "Roma" }, value: "Roma" }
  ],
  "Spain": [
    { label: { en: "Madrid", zh: "Madrid" }, value: "Madrid" },
    { label: { en: "Barcelona", zh: "Barcelona" }, value: "Barcelona" },
    { label: { en: "Getafe", zh: "Getafe" }, value: "Getafe" }
  ],
  "Malaysia": [
    { label: { en: "Kuala Lumpur", zh: "Kuala Lumpur" }, value: "Kuala Lumpur" },
    { label: { en: "Kulim, Kedah", zh: "Kulim, Kedah" }, value: "Kulim, Kedah" },
    { label: { en: "Penang", zh: "Penang" }, value: "Penang" },
    { label: { en: "Petaling Jaya", zh: "Petaling Jaya" }, value: "Petaling Jaya" },
    { label: { en: "Selangor", zh: "Selangor" }, value: "Selangor" }
  ],
  "Netherlands": [
    { label: { en: "Amsterdam", zh: "Amsterdam" }, value: "Amsterdam" },
    { label: { en: "Rotterdam", zh: "Rotterdam" }, value: "Rotterdam" },
    { label: { en: "Utrecht", zh: "Utrecht" }, value: "Utrecht" },
    { label: { en: "Eindhoven", zh: "Eindhoven" }, value: "Eindhoven" },
    { label: { en: "Boxmeer, North Brabant", zh: "Boxmeer, North Brabant" }, value: "Boxmeer, North Brabant" }
  ],
  "Brazil": [
    { label: { en: "São Paulo", zh: "São Paulo" }, value: "São Paulo" },
    { label: { en: "São Paulo, SP", zh: "São Paulo, SP" }, value: "São Paulo, SP" },
    { label: { en: "Rio De Janeiro", zh: "Rio De Janeiro" }, value: "Rio De Janeiro" },
    { label: { en: "Sao Paulo", zh: "Sao Paulo" }, value: "Sao Paulo" },
    { label: { en: "Sao Paulo, SP", zh: "Sao Paulo, SP" }, value: "Sao Paulo, SP" }
  ],
  "Mexico": [
    { label: { en: "Mexico City", zh: "Mexico City" }, value: "Mexico City" },
    { label: { en: "Guadalajara", zh: "Guadalajara" }, value: "Guadalajara" },
    { label: { en: "Monterrey", zh: "Monterrey" }, value: "Monterrey" },
    { label: { en: "Mexico, Mexico", zh: "Mexico, Mexico" }, value: "Mexico, Mexico" },
    { label: { en: "Reynosa", zh: "Reynosa" }, value: "Reynosa" }
  ],
  "Poland": [
    { label: { en: "Warsaw", zh: "Warsaw" }, value: "Warsaw" },
    { label: { en: "Krakow", zh: "Krakow" }, value: "Krakow" },
    { label: { en: "Gdansk", zh: "Gdansk" }, value: "Gdansk" },
    { label: { en: "Poznan", zh: "Poznan" }, value: "Poznan" },
    { label: { en: "Katowice", zh: "Katowice" }, value: "Katowice" },
    { label: { en: "Kraków", zh: "Kraków" }, value: "Kraków" },
    { label: { en: "Poznań", zh: "Poznań" }, value: "Poznań" },
    { label: { en: "Warszawa", zh: "Warszawa" }, value: "Warszawa" },
    { label: { en: "Wrocław", zh: "Wrocław" }, value: "Wrocław" }
  ],
  "Philippines": [
    { label: { en: "Manila", zh: "Manila" }, value: "Manila" },
    { label: { en: "Quezon City", zh: "Quezon City" }, value: "Quezon City" },
    { label: { en: "Cebu", zh: "Cebu" }, value: "Cebu" },
    { label: { en: "Makati", zh: "Makati" }, value: "Makati" },
    { label: { en: "Makati City", zh: "Makati City" }, value: "Makati City" },
    { label: { en: "Pasig", zh: "Pasig" }, value: "Pasig" },
    { label: { en: "Pasig City", zh: "Pasig City" }, value: "Pasig City" },
    { label: { en: "Taguig", zh: "Taguig" }, value: "Taguig" },
    { label: { en: "Taguig City", zh: "Taguig City" }, value: "Taguig City" }
  ],
  "Germany": [
    { label: { en: "Berlin", zh: "Berlin" }, value: "Berlin" },
    { label: { en: "Munich", zh: "Munich" }, value: "Munich" },
    { label: { en: "Hamburg", zh: "Hamburg" }, value: "Hamburg" },
    { label: { en: "Frankfurt", zh: "Frankfurt" }, value: "Frankfurt" },
    { label: { en: "Stuttgart", zh: "Stuttgart" }, value: "Stuttgart" },
    { label: { en: "Bremen", zh: "Bremen" }, value: "Bremen" },
    { label: { en: "Düsseldorf", zh: "Düsseldorf" }, value: "Düsseldorf" },
    { label: { en: "Freiburg", zh: "Freiburg" }, value: "Freiburg" },
    { label: { en: "Gütersloh", zh: "Gütersloh" }, value: "Gütersloh" },
    { label: { en: "Kiel", zh: "Kiel" }, value: "Kiel" },
    { label: { en: "Köln", zh: "Köln" }, value: "Köln" },
    { label: { en: "München", zh: "München" }, value: "München" }
  ],
  "Japan": [
    { label: { en: "Tokyo", zh: "东京" }, value: "Tokyo" },
    { label: { en: "Osaka", zh: "大阪" }, value: "Osaka" },
    { label: { en: "Yokohama", zh: "横滨" }, value: "Yokohama" },
    { label: { en: "Minato", zh: "港区" }, value: "Minato" },
    { label: { en: "Sumida", zh: "墨田区" }, value: "Sumida" }
  ],
      "Canada": [
    { label: { en: "Toronto, ON", zh: "多伦多, 安大略省" }, value: "Toronto, ON" },
    { label: { en: "Vancouver, BC", zh: "温哥华, 不列颠哥伦比亚省" }, value: "Vancouver, BC" },
    { label: { en: "Montreal, QC", zh: "蒙特利尔, 魁北克省" }, value: "Montreal, QC" },
    { label: { en: "Calgary, AB", zh: "卡尔加里, 艾伯塔省" }, value: "Calgary, AB" },
    { label: { en: "Ottawa, ON", zh: "渥太华, 安大略省" }, value: "Ottawa, ON" },
    { label: { en: "Edmonton, AB", zh: "埃德蒙顿, 艾伯塔省" }, value: "Edmonton, AB" },
    { label: { en: "Winnipeg, MB", zh: "温尼伯, 马尼托巴省" }, value: "Winnipeg, MB" },
    { label: { en: "Markham, ON", zh: "万锦, 安大略省" }, value: "Markham, ON" },
    { label: { en: "Mirabel, QC", zh: "Mirabel, 魁北克省" }, value: "Mirabel, QC" },
    { label: { en: "Mississauga, ON", zh: "密西沙加, 安大略省" }, value: "Mississauga, ON" },
    { label: { en: "Scarborough, ON", zh: "士嘉堡, 安大略省" }, value: "Scarborough, ON" }
  ,
    { label: { en: "Quebec, QC", zh: "魁北克, 魁北克省" }, value: "Quebec, QC" }
  ],
      "India": [
    { label: { en: "Mumbai, MH", zh: "孟买, 马哈拉施特拉邦" }, value: "Mumbai, MH" },
    { label: { en: "Delhi, DL", zh: "德里, 德里" }, value: "Delhi, DL" },
    { label: { en: "Bangalore, KA", zh: "班加罗尔, 卡纳塔克邦" }, value: "Bangalore, KA" },
    { label: { en: "Hyderabad, TG", zh: "海得拉巴, 特伦甘纳邦" }, value: "Hyderabad, TG" },
    { label: { en: "Chennai", zh: "金奈" }, value: "Chennai" },
    { label: { en: "Kolkata", zh: "加尔各答" }, value: "Kolkata" },
    { label: { en: "Pune, MH", zh: "浦那, 马哈拉施特拉邦" }, value: "Pune, MH" },
    { label: { en: "Ahmedabad", zh: "艾哈迈达巴德" }, value: "Ahmedabad" },
    { label: { en: "Gurugram", zh: "古尔冈" }, value: "Gurugram" },
    { label: { en: "Noida", zh: "诺伊达" }, value: "Noida" }
  ],
    "United States": [
    { label: { en: "New York, NY", zh: "New York, 纽约州" }, value: "New York, NY" },
    { label: { en: "Boston, MA", zh: "Boston, 马萨诸塞州" }, value: "Boston, MA" },
    { label: { en: "San Francisco, CA", zh: "San Francisco, 加利福尼亚州" }, value: "San Francisco, CA" },
    { label: { en: "Seattle, WA", zh: "Seattle, 华盛顿州" }, value: "Seattle, WA" },
    { label: { en: "Chicago, IL", zh: "Chicago, 伊利诺伊州" }, value: "Chicago, IL" },
    { label: { en: "Los Angeles, CA", zh: "Los Angeles, 加利福尼亚州" }, value: "Los Angeles, CA" },
    { label: { en: "Aiken, SC", zh: "Aiken, 南卡罗来纳州" }, value: "Aiken, SC" },
    { label: { en: "Albuquerque, NM", zh: "阿尔伯克基, 新墨西哥州" }, value: "Albuquerque, NM" },
    { label: { en: "Americas, TX", zh: "Americas, 得克萨斯州" }, value: "Americas, TX" },
    { label: { en: "Ames, IA", zh: "埃姆斯, 艾奥瓦州" }, value: "Ames, IA" },
    { label: { en: "Anchorage, AK", zh: "安克雷奇, 阿拉斯加州" }, value: "Anchorage, AK" },
    { label: { en: "Anderson, SC", zh: "Anderson, 南卡罗来纳州" }, value: "Anderson, SC" },
    { label: { en: "Antelope Valley, CA", zh: "Antelope Valley, 加利福尼亚州" }, value: "Antelope Valley, CA" },
    { label: { en: "Apache Junction, AZ", zh: "阿帕奇章克申, 亚利桑那州" }, value: "Apache Junction, AZ" },
    { label: { en: "Arvin, CA", zh: "阿尔文, 加利福尼亚州" }, value: "Arvin, CA" },
    { label: { en: "Atlanta, GA", zh: "Atlanta, 佐治亚州" }, value: "Atlanta, GA" },
    { label: { en: "Austin, TX", zh: "Austin, 得克萨斯州" }, value: "Austin, TX" },
    { label: { en: "Bakersfield, CA", zh: "贝克斯菲尔德, 加利福尼亚州" }, value: "Bakersfield, CA" },
    { label: { en: "Baltimore, MD", zh: "Baltimore, 马里兰州" }, value: "Baltimore, MD" },
    { label: { en: "Banning, CA", zh: "班宁, 加利福尼亚州" }, value: "Banning, CA" },
    { label: { en: "Batesville, AR", zh: "贝茨维尔, 阿肯色州" }, value: "Batesville, AR" },
    { label: { en: "Baton Rouge, LA", zh: "Baton Rouge, 路易斯安那州" }, value: "Baton Rouge, LA" },
    { label: { en: "Beachwood, OH", zh: "Beachwood, 俄亥俄州" }, value: "Beachwood, OH" },
    { label: { en: "Bethel Park, PA", zh: "Bethel Park, 宾夕法尼亚州" }, value: "Bethel Park, PA" },
    { label: { en: "Bishop, CA", zh: "毕晓普, 加利福尼亚州" }, value: "Bishop, CA" },
    { label: { en: "Boulder, CO", zh: "Boulder, 科罗拉多州" }, value: "Boulder, CO" },
    { label: { en: "Buffalo, NY", zh: "布法罗, 纽约州" }, value: "Buffalo, NY" },
    { label: { en: "Burlingame, CA", zh: "伯林盖姆, 加利福尼亚州" }, value: "Burlingame, CA" },
    { label: { en: "Cambridge, MA", zh: "剑桥, 马萨诸塞州" }, value: "Cambridge, MA" },
    { label: { en: "Canonsburg, PA", zh: "卡农斯堡, 宾夕法尼亚州" }, value: "Canonsburg, PA" },
    { label: { en: "Carmichael, CA", zh: "卡迈克尔, 加利福尼亚州" }, value: "Carmichael, CA" },
    { label: { en: "Castro Valley, CA", zh: "卡斯特罗谷, 加利福尼亚州" }, value: "Castro Valley, CA" },
    { label: { en: "Charleston, SC", zh: "Charleston, 南卡罗来纳州" }, value: "Charleston, SC" },
    { label: { en: "Charlotte, NC", zh: "Charlotte, 北卡罗来纳州" }, value: "Charlotte, NC" },
    { label: { en: "Cherry Valley, CA", zh: "樱桃谷, 加利福尼亚州" }, value: "Cherry Valley, CA" },
    { label: { en: "Cincinnati, OH", zh: "Cincinnati, 俄亥俄州" }, value: "Cincinnati, OH" },
    { label: { en: "Cleveland, OH", zh: "克利夫兰, 俄亥俄州" }, value: "Cleveland, OH" },
    { label: { en: "Clovis, CA", zh: "克洛维斯, 加利福尼亚州" }, value: "Clovis, CA" },
    { label: { en: "Coal Creek, CO", zh: "Coal Creek, 科罗拉多州" }, value: "Coal Creek, CO" },
    { label: { en: "College Park, MD", zh: "College Park, 马里兰州" }, value: "College Park, MD" },
    { label: { en: "College Station, TX", zh: "College Station, 得克萨斯州" }, value: "College Station, TX" },
    { label: { en: "Colorado Springs, CO", zh: "科罗拉多斯普林斯, 科罗拉多州" }, value: "Colorado Springs, CO" },
    { label: { en: "Columbia, SC", zh: "Columbia, 南卡罗来纳州" }, value: "Columbia, SC" },
    { label: { en: "Columbus, OH", zh: "Columbus, 俄亥俄州" }, value: "Columbus, OH" },
    { label: { en: "Concord, CA", zh: "康科德, 加利福尼亚州" }, value: "Concord, CA" },
    { label: { en: "Concord, NC", zh: "康科德, 北卡罗来纳州" }, value: "Concord, NC" },
    { label: { en: "Coppell, TX", zh: "科佩尔, 得克萨斯州" }, value: "Coppell, TX" },
    { label: { en: "Coral Gables, FL", zh: "科勒尔盖布尔斯, 佛罗里达州" }, value: "Coral Gables, FL" },
    { label: { en: "Corpus Christi, TX", zh: "科珀斯克里斯蒂, 得克萨斯州" }, value: "Corpus Christi, TX" },
    { label: { en: "Dallas, TX", zh: "Dallas, 得克萨斯州" }, value: "Dallas, TX" },
    { label: { en: "Denver, CO", zh: "Denver, 科罗拉多州" }, value: "Denver, CO" },
    { label: { en: "Detroit, MI", zh: "Detroit, 密歇根州" }, value: "Detroit, MI" },
    { label: { en: "Doral, FL", zh: "多拉尔, 佛罗里达州" }, value: "Doral, FL" },
    { label: { en: "Dublin, OH", zh: "都柏林, 俄亥俄州" }, value: "Dublin, OH" },
    { label: { en: "Eagle Ridge, CO", zh: "Eagle Ridge, 科罗拉多州" }, value: "Eagle Ridge, CO" },
    { label: { en: "Easley, SC", zh: "Easley, 南卡罗来纳州" }, value: "Easley, SC" },
    { label: { en: "Edgefield, SC", zh: "埃奇菲尔德, 南卡罗来纳州" }, value: "Edgefield, SC" },
    { label: { en: "El Paso, TX", zh: "El Paso, 得克萨斯州" }, value: "El Paso, TX" },
    { label: { en: "Farmington Hills, MI", zh: "法明顿希尔斯, 密歇根州" }, value: "Farmington Hills, MI" },
    { label: { en: "Fayetteville, AR", zh: "Fayetteville, 阿肯色州" }, value: "Fayetteville, AR" },
    { label: { en: "Fort Smith, AR", zh: "Fort Smith, 阿肯色州" }, value: "Fort Smith, AR" },
    { label: { en: "Fort Worth, TX", zh: "Fort Worth, 得克萨斯州" }, value: "Fort Worth, TX" },
    { label: { en: "Fountain Inn, SC", zh: "Fountain Inn, 南卡罗来纳州" }, value: "Fountain Inn, SC" },
    { label: { en: "Fresno, CA", zh: "弗雷斯诺, 加利福尼亚州" }, value: "Fresno, CA" },
    { label: { en: "Grand Rapids, MI", zh: "大急流城, 密歇根州" }, value: "Grand Rapids, MI" },
    { label: { en: "Green Bay, WI", zh: "绿湾, 威斯康星州" }, value: "Green Bay, WI" },
    { label: { en: "Greensboro, NC", zh: "格林斯伯勒, 北卡罗来纳州" }, value: "Greensboro, NC" },
    { label: { en: "Greenville, SC", zh: "Greenville, 南卡罗来纳州" }, value: "Greenville, SC" },
    { label: { en: "Greer, SC", zh: "Greer, 南卡罗来纳州" }, value: "Greer, SC" },
    { label: { en: "Hanford, CA", zh: "汉福德, 加利福尼亚州" }, value: "Hanford, CA" },
    { label: { en: "Harrisburg, PA", zh: "哈里斯堡, 宾夕法尼亚州" }, value: "Harrisburg, PA" },
    { label: { en: "Helena, AR", zh: "Helena, 阿肯色州" }, value: "Helena, AR" },
    { label: { en: "Hemet, CA", zh: "赫米特, 加利福尼亚州" }, value: "Hemet, CA" },
    { label: { en: "Hershey, PA", zh: "Hershey, 宾夕法尼亚州" }, value: "Hershey, PA" },
    { label: { en: "Highland, CA", zh: "高地, 加利福尼亚州" }, value: "Highland, CA" },
    { label: { en: "Highline, CO", zh: "Highline, 科罗拉多州" }, value: "Highline, CO" },
    { label: { en: "Honolulu, HI", zh: "檀香山, 夏威夷州" }, value: "Honolulu, HI" },
    { label: { en: "Hope, AR", zh: "Hope, 阿肯色州" }, value: "Hope, AR" },
    { label: { en: "Houston, TX", zh: "Houston, 得克萨斯州" }, value: "Houston, TX" },
    { label: { en: "Indianapolis, IN", zh: "Indianapolis, 印第安纳州" }, value: "Indianapolis, IN" },
    { label: { en: "Irvine, CA", zh: "尔湾, 加利福尼亚州" }, value: "Irvine, CA" },
    { label: { en: "Irving, TX", zh: "欧文, 得克萨斯州" }, value: "Irving, TX" },
    { label: { en: "Iva, SC", zh: "Iva, 南卡罗来纳州" }, value: "Iva, SC" },
    { label: { en: "Jacksonville, FL", zh: "Jacksonville, 佛罗里达州" }, value: "Jacksonville, FL" },
    { label: { en: "Johns Island, SC", zh: "Johns Island, 南卡罗来纳州" }, value: "Johns Island, SC" },
    { label: { en: "La Mesa, CA", zh: "La Mesa, 加利福尼亚州" }, value: "La Mesa, CA" },
    { label: { en: "Lakeport, CA", zh: "莱克波特, 加利福尼亚州" }, value: "Lakeport, CA" },
    { label: { en: "Lakewood, CO", zh: "Lakewood, 科罗拉多州" }, value: "Lakewood, CO" },
    { label: { en: "Lancaster, OH", zh: "Lancaster, 俄亥俄州" }, value: "Lancaster, OH" },
    { label: { en: "Las Vegas, NV", zh: "Las Vegas, 内华达州" }, value: "Las Vegas, NV" },
    { label: { en: "Lincoln, CA", zh: "林肯, 加利福尼亚州" }, value: "Lincoln, CA" },
    { label: { en: "Lincoln, NE", zh: "林肯, 内布拉斯加州" }, value: "Lincoln, NE" },
    { label: { en: "Little Rock, AR", zh: "Little Rock, 阿肯色州" }, value: "Little Rock, AR" },
    { label: { en: "Loma Linda, CA", zh: "洛马琳达, 加利福尼亚州" }, value: "Loma Linda, CA" },
    { label: { en: "Louisville, KY", zh: "Louisville, 肯塔基州" }, value: "Louisville, KY" },
    { label: { en: "Madison, WI", zh: "麦迪逊, 威斯康星州" }, value: "Madison, WI" },
    { label: { en: "Maplewood, MN", zh: "Maplewood, 明尼苏达州" }, value: "Maplewood, MN" },
    { label: { en: "Marietta, SC", zh: "玛丽埃塔, 南卡罗来纳州" }, value: "Marietta, SC" },
    { label: { en: "Marysville, CA", zh: "玛丽斯维尔, 加利福尼亚州" }, value: "Marysville, CA" },
    { label: { en: "McCormick, SC", zh: "McCormick, 南卡罗来纳州" }, value: "McCormick, SC" },
    { label: { en: "McLean, VA", zh: "McLean, 弗吉尼亚州" }, value: "McLean, VA" },
    { label: { en: "Medford, OR", zh: "梅德福, 俄勒冈州" }, value: "Medford, OR" },
    { label: { en: "Memphis, TN", zh: "Memphis, 田纳西州" }, value: "Memphis, TN" },
    { label: { en: "Mena, AR", zh: "米纳, 阿肯色州" }, value: "Mena, AR" },
    { label: { en: "Menlo Park, CA", zh: "Menlo Park, 加利福尼亚州" }, value: "Menlo Park, CA" },
    { label: { en: "Miami, FL", zh: "Miami, 佛罗里达州" }, value: "Miami, FL" },
    { label: { en: "Milwaukee, WI", zh: "Milwaukee, 威斯康星州" }, value: "Milwaukee, WI" },
    { label: { en: "Minneapolis, MN", zh: "明尼阿波利斯, 明尼苏达州" }, value: "Minneapolis, MN" },
    { label: { en: "Modesto, CA", zh: "莫德斯托, 加利福尼亚州" }, value: "Modesto, CA" },
    { label: { en: "Monroeville, PA", zh: "门罗维尔, 宾夕法尼亚州" }, value: "Monroeville, PA" },
    { label: { en: "Monticello, AR", zh: "Monticello, 阿肯色州" }, value: "Monticello, AR" },
    { label: { en: "Morrilton, AR", zh: "Morrilton, 阿肯色州" }, value: "Morrilton, AR" },
    { label: { en: "Mountain View, WA", zh: "Mountain View, 华盛顿州" }, value: "Mountain View, WA" },
    { label: { en: "Napa, CA", zh: "纳帕, 加利福尼亚州" }, value: "Napa, CA" },
    { label: { en: "Nashville, TN", zh: "Nashville, 田纳西州" }, value: "Nashville, TN" },
    { label: { en: "New Orleans, LA", zh: "新奥尔良, 路易斯安那州" }, value: "New Orleans, LA" },
    { label: { en: "New York City, NY", zh: "New York City, 纽约州" }, value: "New York City, NY" },
    { label: { en: "Norfolk, VA", zh: "诺福克, 弗吉尼亚州" }, value: "Norfolk, VA" },
    { label: { en: "North Houston, TX", zh: "North Houston, 得克萨斯州" }, value: "North Houston, TX" },
    { label: { en: "North Little Rock, AR", zh: "North Little Rock, 阿肯色州" }, value: "North Little Rock, AR" },
    { label: { en: "North Royalton, OH", zh: "North Royalton, 俄亥俄州" }, value: "North Royalton, OH" },
    { label: { en: "Oakland, CA", zh: "奥克兰, 加利福尼亚州" }, value: "Oakland, CA" },
    { label: { en: "Oklahoma City, OK", zh: "Oklahoma City, 俄克拉荷马州" }, value: "Oklahoma City, OK" },
    { label: { en: "Omaha, NE", zh: "奥马哈, 内布拉斯加州" }, value: "Omaha, NE" },
    { label: { en: "Orangeburg, SC", zh: "奥兰治堡, 南卡罗来纳州" }, value: "Orangeburg, SC" },
    { label: { en: "Orlando, FL", zh: "奥兰多, 佛罗里达州" }, value: "Orlando, FL" },
    { label: { en: "Oshkosh, WI", zh: "奥什科什, 威斯康星州" }, value: "Oshkosh, WI" },
    { label: { en: "Palm Desert, CA", zh: "棕榈沙漠, 加利福尼亚州" }, value: "Palm Desert, CA" },
    { label: { en: "Palo Alto, CA", zh: "帕洛阿尔托, 加利福尼亚州" }, value: "Palo Alto, CA" },
    { label: { en: "Philadelphia, PA", zh: "Philadelphia, 宾夕法尼亚州" }, value: "Philadelphia, PA" },
    { label: { en: "Phoenix, AZ", zh: "Phoenix, 亚利桑那州" }, value: "Phoenix, AZ" },
    { label: { en: "Pickens, SC", zh: "Pickens, 南卡罗来纳州" }, value: "Pickens, SC" },
    { label: { en: "Piedmont, SC", zh: "Piedmont, 南卡罗来纳州" }, value: "Piedmont, SC" },
    { label: { en: "Pikes Peak, CO", zh: "Pikes Peak, 科罗拉多州" }, value: "Pikes Peak, CO" },
    { label: { en: "Pine Bluff, AR", zh: "Pine Bluff, 阿肯色州" }, value: "Pine Bluff, AR" },
    { label: { en: "Pittsburgh, PA", zh: "Pittsburgh, 宾夕法尼亚州" }, value: "Pittsburgh, PA" },
    { label: { en: "Placerville, CA", zh: "普拉瑟维尔, 加利福尼亚州" }, value: "Placerville, CA" },
    { label: { en: "Plano, TX", zh: "普莱诺, 得克萨斯州" }, value: "Plano, TX" },
    { label: { en: "Pleasanton, CA", zh: "Pleasanton, 加利福尼亚州" }, value: "Pleasanton, CA" },
    { label: { en: "Porterville, CA", zh: "波特维尔, 加利福尼亚州" }, value: "Porterville, CA" },
    { label: { en: "Portland, OR", zh: "Portland, 俄勒冈州" }, value: "Portland, OR" },
    { label: { en: "Providence, RI", zh: "普罗维登斯, 罗得岛州" }, value: "Providence, RI" },
    { label: { en: "Raleigh, NC", zh: "罗利, 北卡罗来纳州" }, value: "Raleigh, NC" },
    { label: { en: "Red Cliffs, CO", zh: "Red Cliffs, 科罗拉多州" }, value: "Red Cliffs, CO" },
    { label: { en: "Reno, NV", zh: "里诺, 内华达州" }, value: "Reno, NV" },
    { label: { en: "Richmond, VA", zh: "Richmond, 弗吉尼亚州" }, value: "Richmond, VA" },
    { label: { en: "Riverdale, CO", zh: "里弗代尔, 科罗拉多州" }, value: "Riverdale, CO" },
    { label: { en: "Riverside, CA", zh: "里弗赛德, 加利福尼亚州" }, value: "Riverside, CA" },
    { label: { en: "Roanoke, VA", zh: "罗阿诺克, 弗吉尼亚州" }, value: "Roanoke, VA" },
    { label: { en: "Rochester, NY", zh: "罗切斯特, 纽约州" }, value: "Rochester, NY" },
    { label: { en: "Rome, GA", zh: "罗马, 佐治亚州" }, value: "Rome, GA" },
    { label: { en: "Roseville, CA", zh: "罗斯维尔, 加利福尼亚州" }, value: "Roseville, CA" },
    { label: { en: "Round Rock, TX", zh: "圆石城, 得克萨斯州" }, value: "Round Rock, TX" },
    { label: { en: "San Antonio, TX", zh: "San Antonio, 得克萨斯州" }, value: "San Antonio, TX" },
    { label: { en: "San Diego, CA", zh: "San Diego, 加利福尼亚州" }, value: "San Diego, CA" },
    { label: { en: "San Jose, CA", zh: "San Jose, 加利福尼亚州" }, value: "San Jose, CA" },
    { label: { en: "Scottsdale, AZ", zh: "斯科茨代尔, 亚利桑那州" }, value: "Scottsdale, AZ" },
    { label: { en: "Simpsonville, SC", zh: "Simpsonville, 南卡罗来纳州" }, value: "Simpsonville, SC" },
    { label: { en: "Sioux Falls, SD", zh: "苏福尔斯, 南达科他州" }, value: "Sioux Falls, SD" },
    { label: { en: "Sonoma, CA", zh: "索诺马, 加利福尼亚州" }, value: "Sonoma, CA" },
    { label: { en: "St. Louis, MO", zh: "St. Louis, 密苏里州" }, value: "St. Louis, MO" },
    { label: { en: "State College, PA", zh: "State College, 宾夕法尼亚州" }, value: "State College, PA" },
    { label: { en: "Sterling, VA", zh: "斯特林, 弗吉尼亚州" }, value: "Sterling, VA" },
    { label: { en: "Stuttgart, AR", zh: "斯图加特, 阿肯色州" }, value: "Stuttgart, AR" },
    { label: { en: "Sunnyvale, CA", zh: "森尼韦尔, 加利福尼亚州" }, value: "Sunnyvale, CA" },
    { label: { en: "Tampa, FL", zh: "Tampa, 佛罗里达州" }, value: "Tampa, FL" },
    { label: { en: "Tempe, AZ", zh: "坦佩, 亚利桑那州" }, value: "Tempe, AZ" },
    { label: { en: "Texarkana, AR", zh: "特克萨卡纳, 阿肯色州" }, value: "Texarkana, AR" },
    { label: { en: "The Woodlands, TX", zh: "林地, 得克萨斯州" }, value: "The Woodlands, TX" },
    { label: { en: "Troy, MI", zh: "Troy, 密歇根州" }, value: "Troy, MI" },
    { label: { en: "Tucson, AZ", zh: "图森, 亚利桑那州" }, value: "Tucson, AZ" },
    { label: { en: "Twinsburg, OH", zh: "Twinsburg, 俄亥俄州" }, value: "Twinsburg, OH" },
    { label: { en: "Union, SC", zh: "尤宁, 南卡罗来纳州" }, value: "Union, SC" },
    { label: { en: "University Park, PA", zh: "University Park, 宾夕法尼亚州" }, value: "University Park, PA" },
    { label: { en: "Virginia Beach, VA", zh: "弗吉尼亚海滩, 弗吉尼亚州" }, value: "Virginia Beach, VA" },
    { label: { en: "Washington, DC", zh: "Washington, 华盛顿特区" }, value: "Washington, DC" },
    { label: { en: "West Palm Beach, FL", zh: "西棕榈滩, 佛罗里达州" }, value: "West Palm Beach, FL" },
    { label: { en: "Westerville, OH", zh: "韦斯特维尔, 俄亥俄州" }, value: "Westerville, OH" },
    { label: { en: "Westwood, CO", zh: "Westwood, 科罗拉多州" }, value: "Westwood, CO" },
    { label: { en: "Wichita, KS", zh: "威奇托, 堪萨斯州" }, value: "Wichita, KS" },
    { label: { en: "Willoughby, OH", zh: "Willoughby, 俄亥俄州" }, value: "Willoughby, OH" },
    { label: { en: "Wilmington, DE", zh: "威尔明顿, 特拉华州" }, value: "Wilmington, DE" },
    { label: { en: "Winston Salem, NC", zh: "Winston Salem, 北卡罗来纳州" }, value: "Winston Salem, NC" },
    { label: { en: "Worcester, MA", zh: "伍斯特, 马萨诸塞州" }, value: "Worcester, MA" }
  ],
  "Ireland": [
    { label: { en: "Cork", zh: "科克" }, value: "Cork" },
    { label: { en: "Limerick", zh: "利默里克" }, value: "Limerick" }
  ],
  "Thailand": [
    { label: { en: "Bangkok", zh: "曼谷" }, value: "Bangkok" }
  ],
  "Peru": [
    { label: { en: "Lima", zh: "利马" }, value: "Lima" }
  ],
  "Turkey": [
    { label: { en: "Istanbul", zh: "伊斯坦布尔" }, value: "Istanbul" }
  ]
} as const;

export type CountryKey = keyof typeof cityOptionsMap;