/**
 * 城市扩展区域定义（GPT 生成）
 * 生成时间: 2025-11-18T08:21:55.863Z
 * 
 * 此文件由 scripts/generateCityExpansions.ts 自动生成
 * 请勿手动修改，如需更新请重新运行生成脚本
 */

export interface GreaterAreaDefinition {
  core: string[];     // 方圆 10 公里以内（权重正常）
  fringe: string[];   // 10–30 公里，次优区域（权重可略降）
}

export const greaterAreaMapExtended: Record<string, GreaterAreaDefinition> = {
  "Adelaide": {
    core: [
      "Adelaide",
      "North Adelaide",
      "Glenelg",
      "Norwood",
      "Unley",
      "Burnside",
      "West Torrens",
      "Mawson Lakes",
      "Port Adelaide",
      "Henley Beach",
      "Prospect",
      "Walkerville",
      "Campbelltown",
      "Findon",
      "West Beach"
    ],
    fringe: [
      "Marden",
      "Salisbury",
      "Elizabeth",
      "Modbury",
      "Tea Tree Gully",
      "Mount Barker",
      "Port Noarlunga",
      "Seaford",
      "Gawler",
      "Lonsdale",
      "Morphett Vale",
      "Christies Beach",
      "Hallett Cove",
      "Aberfoyle Park"
    ]
  },
  "Albany": {
    core: [
      "Albany",
      "Albany CBD",
      "Lockyer",
      "Collingwood Park",
      "Spencer Park",
      "Mount Melville",
      "Yakamia",
      "Mckail",
      "Bayonet Head",
      "Emu Point",
      "Little Grove",
      "Crawley",
      "Mira Mar",
      "Gledhow",
      "Kendenup"
    ],
    fringe: [
      "Denmark",
      "Mount Barker",
      "Torbay",
      "Porongurup",
      "Pindar",
      "Kambalda",
      "Walpole",
      "Nornalup",
      "Kojonup",
      "Jerramungup",
      "Borden",
      "Cranbrook",
      "Frankland"
    ]
  },
  "Albury": {
    core: [
      "Albury",
      "Lavington",
      "West Albury",
      "East Albury",
      "North Albury",
      "South Albury",
      "Thurgoona",
      "Table Top",
      "Borella",
      "Wodonga",
      "Springdale Heights",
      "Albury CBD",
      "Albury Airport",
      "Haven",
      "Glenroy"
    ],
    fringe: [
      "Baranduda",
      "Bonegilla",
      "Kiewa",
      "Yackandandah",
      "Rutherglen",
      "Corowa",
      "Howlong",
      "North Wodonga",
      "South Wodonga",
      "Belvoir Park",
      "Ebden"
    ]
  },
  "Austin": {
    core: [
      "Austin",
      "Downtown Austin",
      "South Congress",
      "East Austin",
      "North Loop",
      "West Lake Hills",
      "Mueller",
      "Travis Heights",
      "The Domain",
      "Barton Hills",
      "Zilker",
      "Tarrytown",
      "Circle C Ranch",
      "Pflugerville",
      "Round Rock"
    ],
    fringe: [
      "Cedar Park",
      "Leander",
      "Georgetown",
      "San Marcos",
      "Kyle",
      "Buda",
      "Lakeway",
      "Hutto",
      "Taylor",
      "Dripping Springs",
      "Manor",
      "Wimberley",
      "Liberty Hill",
      "Bastrop"
    ]
  },
  "Ballarat": {
    core: [
      "Ballarat",
      "Ballarat Central",
      "Lake Wendouree",
      "Redan",
      "Sebastopol",
      "Mount Pleasant",
      "Wendouree",
      "Nerrina",
      "Black Hill",
      "Golden Point",
      "Ballarat East",
      "Ballarat North",
      "Miners Rest",
      "Alfredton",
      "Brown Hill"
    ],
    fringe: [
      "Buninyong",
      "Clunes",
      "Creswick",
      "Daylesford",
      "Gordon",
      "Learmonth",
      "Moorabool",
      "Napoleons",
      "Smythesdale",
      "Yandoit",
      "Scarsdale",
      "Barkly"
    ]
  },
  "Baltimore": {
    core: [
      "Baltimore",
      "Downtown",
      "Inner Harbor",
      "Fells Point",
      "Canton",
      "Federal Hill",
      "Mount Vernon",
      "Charles Village",
      "Patterson Park",
      "Highlandtown",
      "Druid Hill",
      "Woodberry",
      "Greektown",
      "South Baltimore",
      "West Baltimore"
    ],
    fringe: [
      "Towson",
      "Catonsville",
      "Parkville",
      "Pikesville",
      "Randallstown",
      "Reisterstown",
      "Ellicott City",
      "Columbia",
      "Laurel",
      "Owings Mills",
      "Glen Burnie",
      "Severna Park",
      "Bel Air",
      "Aberdeen",
      "Hanover"
    ]
  },
  "Bangalore": {
    core: [
      "Bangalore",
      "MG Road",
      "Indiranagar",
      "Koramangala",
      "Jayanagar",
      "Whitefield",
      "Brigade Road",
      "BTM Layout",
      "Malleshwaram",
      "Shantinagar",
      "Ulsoor",
      "Hosur Road",
      "Electronic City",
      "Sarjapur",
      "Hebbal"
    ],
    fringe: [
      "Mysore Road",
      "Devanahalli",
      "Kengeri",
      "Hoskote",
      "Sarjapur Road",
      "Kanakapura",
      "Nandi Hills",
      "Yelahanka",
      "Vijayanagar",
      "Bannerghatta",
      "Chandapura",
      "Anekal",
      "Doddaballapura",
      "Tumkur",
      "Raja Rajeshwari Nagar"
    ]
  },
  "Bathurst": {
    core: [
      "Bathurst",
      "Kelso",
      "Eglinton",
      "West Bathurst",
      "South Bathurst",
      "Bathurst CBD",
      "Mitchell",
      "Gormans Hill",
      "Little Hartley",
      "O'connell",
      "Raglan",
      "Thornhill Park",
      "Wattle Flat",
      "Perthville",
      "Trunkey Creek"
    ],
    fringe: [
      "Abercrombie",
      "Blayney",
      "Lyndhurst",
      "Mudgee",
      "Oberon",
      "Rylstone",
      "Cowra",
      "Lithgow",
      "Tarana",
      "Wellington",
      "Borenore",
      "Canowindra",
      "Cliefden",
      "Dunedoo",
      "Marrangaroo"
    ]
  },
  "Bendigo": {
    core: [
      "Bendigo",
      "Eaglehawk",
      "Strathdale",
      "Golden Square",
      "Kangaroo Flat",
      "Long Gully",
      "North Bendigo",
      "South Bendigo",
      "White Hills",
      "Flora Hill",
      "California Gully",
      "Bendigo South East",
      "Bendigo Central",
      "Bendigo East",
      "Bendigo West"
    ],
    fringe: [
      "Axedale",
      "Marong",
      "Lockwood",
      "Goornong",
      "Huntly",
      "Sedgwick",
      "Maldon",
      "Baringhup",
      "Elmore",
      "Raywood",
      "Epsom",
      "Bendigo North",
      "Bendigo South",
      "Bendigo North East",
      "Bendigo North West"
    ]
  },
  "Birmingham": {
    core: [
      "Birmingham",
      "Digbeth",
      "Jewellery Quarter",
      "Selly Oak",
      "Edgbaston",
      "Moseley",
      "Kings Heath",
      "Harborne",
      "Bournville",
      "Aston",
      "Ladywood",
      "Sparkbrook",
      "Small Heath",
      "Hodge Hill",
      "Bordesley Green"
    ],
    fringe: [
      "Solihull",
      "Wolverhampton",
      "West Bromwich",
      "Coventry",
      "Tamworth",
      "Sutton Coldfield",
      "Dudley",
      "Walsall",
      "Brierley Hill",
      "Redditch",
      "Kidderminster",
      "Lichfield",
      "Nuneaton",
      "Stourbridge",
      "Bromsgrove"
    ]
  },
  "Boston": {
    core: [
      "Boston",
      "Back Bay",
      "Beacon Hill",
      "South End",
      "Seaport District",
      "Fenway Kenmore",
      "Charlestown",
      "North End",
      "West End",
      "Dorchester",
      "Jamaica Plain",
      "Roxbury",
      "Brighton",
      "South Boston",
      "East Boston"
    ],
    fringe: [
      "Cambridge",
      "Somerville",
      "Brookline",
      "Quincy",
      "Newton",
      "Malden",
      "Medford",
      "Everett",
      "Chelsea",
      "Revere",
      "Waltham",
      "Watertown",
      "Braintree",
      "Framingham",
      "Dedham"
    ]
  },
  "Bunbury": {
    core: [
      "Bunbury",
      "East Bunbury",
      "South Bunbury",
      "Bunbury CBD",
      "West Bunbury",
      "Dalyellup",
      "Glen Iris",
      "Withers",
      "Carey Park",
      "Australind",
      "Leschenault",
      "Eaton",
      "Pelican Point",
      "Bunbury Harbour",
      "Picton"
    ],
    fringe: [
      "Donnybrook",
      "Collie",
      "Capel",
      "Boyanup",
      "Brunswick Junction",
      "Mumballup",
      "Wellington Mill",
      "Burekup",
      "Dardanup",
      "Cookernup",
      "Henty",
      "Nannup",
      "Waroona",
      "Harvey",
      "Lake Clifton"
    ]
  },
  "Bundaberg": {
    core: [
      "Bundaberg",
      "Bundaberg East",
      "Bundaberg South",
      "Bundaberg North",
      "Avoca",
      "Kepnock",
      "Branyan",
      "Thabeban",
      "Norville",
      "Qunaba",
      "Burnett Heads",
      "Bargara",
      "Coral Cove",
      "Gooburrum",
      "Millewa"
    ],
    fringe: [
      "Gin Gin",
      "Childers",
      "Woodgate",
      "Elliott Heads",
      "South Kolan",
      "Bucca",
      "Miriam Vale",
      "Rosedale",
      "Biggenden",
      "Mount Perry",
      "Kolan",
      "Apple Tree Creek",
      "Wallaville",
      "Yandaran",
      "Burnett River"
    ]
  },
  "Cairns": {
    core: [
      "Cairns",
      "Cairns North",
      "Edge Hill",
      "Manoora",
      "Westcourt",
      "Bungalow",
      "Parramatta Park",
      "Portsmith",
      "Freshwater",
      "Redlynch",
      "Smithfield",
      "Trinity Beach",
      "Palm Cove",
      "Kewarra Beach",
      "Earlville"
    ],
    fringe: [
      "Aeroglen",
      "Bentley Park",
      "Brinsmead",
      "Caravonica",
      "Clifton Beach",
      "Holloways Beach",
      "Mooroobool",
      "Mount Sheridan",
      "Woree",
      "Yorkeys Knob",
      "Kuranda",
      "Babinda"
    ]
  },
  "Calgary": {
    core: [
      "Calgary",
      "Downtown Calgary",
      "Beltline",
      "Inglewood",
      "Mission",
      "Kensington",
      "Mount Royal",
      "Victoria Park",
      "East Village",
      "Bridgeland",
      "Hillhurst",
      "Ramsay",
      "South Calgary",
      "Copperfield",
      "Walden"
    ],
    fringe: [
      "Airdrie",
      "Cochrane",
      "Okotoks",
      "Chestermere",
      "Strathmore",
      "Rocky View County",
      "Calgary County",
      "High River",
      "Langdon",
      "Heritage Pointe",
      "Sundance",
      "Mckenzie Towne",
      "Tuscany",
      "Royal Oak"
    ]
  },
  "Canberra": {
    core: [
      "Canberra",
      "Belconnen",
      "Gungahlin",
      "Woden",
      "Tuggeranong",
      "Queanbeyan",
      "Narrabundah",
      "Braddon",
      "Dickson",
      "Civic",
      "Lyneham",
      "O'connor",
      "Kambah",
      "Hawker",
      "Farrer"
    ],
    fringe: [
      "Mitchell",
      "Jerrabomberra",
      "Ngunnawal",
      "Charnwood",
      "Kaleen",
      "Giralang",
      "Holt",
      "Duffy",
      "Latham",
      "Mawson",
      "Fadden",
      "Bonython",
      "Gordon",
      "Wanniassa",
      "Rivett"
    ]
  },
  "Causeway Bay": {
    core: [
      "Causeway Bay",
      "Tin Hau",
      "Wanchai",
      "Admiralty",
      "Central",
      "Happy Valley",
      "East Point City",
      "Victoria Park",
      "Shau Kei Wan",
      "North Point",
      "Wan Chai North",
      "Soho",
      "Tsim Sha Tsui",
      "Mong Kok",
      "Jordan"
    ],
    fringe: [
      "Chai Wan",
      "Quarry Bay",
      "Sai Wan Ho",
      "Aberdeen",
      "Wong Chuk Hang",
      "Kowloon Bay",
      "Ngau Tau Kok",
      "Lam Tin",
      "Yau Tong",
      "Tseung Kwan O",
      "Tsing Yi",
      "Tsuen Wan",
      "Sha Tin",
      "Fanling",
      "Tai Po"
    ]
  },
  "Central": {
    core: [
      "Central",
      "Admiralty",
      "Sheung Wan",
      "Soho",
      "Mid Levels",
      "Hong Kong Island East",
      "Tsim Sha Tsui",
      "Wan Chai",
      "Causeway Bay",
      "Kowloon",
      "Mong Kok",
      "Yau Ma Tei",
      "Jordan",
      "Tsim Sha Tsui East",
      "East Tsim Sha Tsui"
    ],
    fringe: [
      "North Point",
      "Quarry Bay",
      "Chai Wan",
      "Sai Wan Ho",
      "Shau Kei Wan",
      "Wong Chuk Hang",
      "Aberdeen",
      "Tin Hau",
      "Tai Koo",
      "Choi Hung",
      "Kowloon Bay",
      "Ngau Tau Kok",
      "Lam Tin",
      "Yau Tong",
      "Tseung Kwan O"
    ]
  },
  "Central Region": {
    core: [
      "Central Region",
      "Central",
      "Admiralty",
      "Sheung Wan",
      "Wan Chai",
      "Causeway Bay",
      "Mid Levels",
      "Soho",
      "Chater Garden",
      "Hong Kong Park",
      "Pacific Place",
      "The Landmark",
      "IFC",
      "Lan Kwai Fong",
      "Cultural Centre",
      "Tsim Sha Tsui"
    ],
    fringe: [
      "Kowloon",
      "Mong Kok",
      "Hung Hom",
      "Yau Ma Tei",
      "Jordan",
      "Sham Shui Po",
      "North Point",
      "Quarry Bay",
      "Chai Wan",
      "Sai Wan Ho",
      "Wong Chuk Hang",
      "Aberdeen",
      "Stanley",
      "Lamma Island"
    ]
  },
  "Charlotte": {
    core: [
      "Charlotte",
      "South End",
      "Uptown",
      "Ballantyne",
      "Dilworth",
      "Noda",
      "Plaza Midwood",
      "University City",
      "South Park",
      "Eastover",
      "Myers Park",
      "Mint Hill",
      "West Charlotte",
      "Cornelius",
      "Huntersville"
    ],
    fringe: [
      "Matthews",
      "Concord",
      "Gastonia",
      "Mooresville",
      "Lake Norman",
      "Fort Mill",
      "Indian Trail",
      "Pineville",
      "Rock Hill",
      "Belmont",
      "Harrisburg",
      "Davidson",
      "Stanley",
      "Union County"
    ]
  },
  "Chicago": {
    core: [
      "Chicago",
      "The Loop",
      "Lincoln Park",
      "Lakeview",
      "Hyde Park",
      "West Loop",
      "South Loop",
      "Wicker Park",
      "Bucktown",
      "River North",
      "Gold Coast",
      "Chinatown",
      "Bridgeport",
      "Pilsen",
      "Andersonville"
    ],
    fringe: [
      "Evanston",
      "Oak Park",
      "Skokie",
      "Cicero",
      "Berwyn",
      "Elmhurst",
      "Schaumburg",
      "Tinley Park",
      "Des Plaines",
      "Hoffman Estates",
      "Downers Grove",
      "Naperville",
      "Wheaton",
      "Orland Park",
      "Lombard"
    ]
  },
  "Coffs Harbour": {
    core: [
      "Coffs Harbour",
      "Toormina",
      "Sawtell",
      "Emerald Beach",
      "Korora",
      "Moonee Beach",
      "Bellingen",
      "Urunga",
      "Woolgoolga",
      "Nambucca Heads",
      "Sandy Beach",
      "Dorrigo",
      "Bonville",
      "Coffs Harbour Jetty",
      "Coffs Harbour CBD"
    ],
    fringe: [
      "Macksville",
      "Repton",
      "Thora",
      "Valla Beach",
      "Coramba",
      "Coffs Harbour South",
      "Coffs Harbour North",
      "Karnak",
      "Mullaway"
    ]
  },
  "Columbus": {
    core: [
      "Columbus",
      "Downtown",
      "Short North",
      "German Village",
      "Arena District",
      "Franklinton",
      "University District",
      "Clintonville",
      "Bexley",
      "Grandview Heights",
      "South Columbus",
      "East Columbus",
      "West Columbus",
      "Northland",
      "Hilltop"
    ],
    fringe: [
      "Dublin",
      "Westerville",
      "Gahanna",
      "Reynoldsburg",
      "Pickerington",
      "Hilliard",
      "Canal Winchester",
      "Blacklick",
      "Pataskala",
      "Lewis Center",
      "Powell",
      "New Albany",
      "Whitehall",
      "Worthington",
      "Upper Arlington"
    ]
  },
  "Dallas": {
    core: [
      "Dallas",
      "Uptown",
      "Deep Ellum",
      "Victory Park",
      "Oak Lawn",
      "West End",
      "Design District",
      "Southlake",
      "Preston Center",
      "Lakewood",
      "Bishop Arts District",
      "Farmers Market",
      "Highland Park",
      "Richardson",
      "Addison"
    ],
    fringe: [
      "Irving",
      "Garland",
      "Mesquite",
      "Carrollton",
      "Frisco",
      "Plano",
      "Lewisville",
      "Rowlett",
      "Duncanville",
      "Cedar Hill",
      "Grand Prairie",
      "Desoto",
      "Wylie",
      "Rockwall",
      "Sunnyvale"
    ]
  },
  "Darwin": {
    core: [
      "Darwin",
      "Larrakeyah",
      "Parap",
      "Fannie Bay",
      "Coconut Grove",
      "Nightcliff",
      "Rapid Creek",
      "Wanguri",
      "Karama",
      "Moil",
      "Casuarina",
      "Berrimah",
      "Humpty Doo",
      "Palmerston",
      "Virginia"
    ],
    fringe: [
      "Palmerston City",
      "Howard Springs",
      "Gunn Point",
      "Mcarthur",
      "Raaf Base Darwin",
      "Coolalinga",
      "Marrara",
      "Jabiru",
      "Katherine",
      "Litchfield",
      "Berry Springs"
    ]
  },
  "Delhi": {
    core: [
      "Delhi",
      "Connaught Place",
      "Gurgaon",
      "Noida",
      "South Delhi",
      "Dwarka",
      "Lajpat Nagar",
      "Karol Bagh",
      "Vasant Kunj",
      "Greater Kailash",
      "Saket",
      "Janakpuri",
      "Rohini",
      "Pitampura",
      "Shahdara"
    ],
    fringe: [
      "Faridabad",
      "Ghaziabad",
      "Sonipat",
      "Narela",
      "Bawana",
      "Dwarka Sector 21",
      "Sultanpur",
      "Mundka",
      "Kapashera",
      "Badarpur",
      "Khanpur",
      "Najafgarh",
      "Sangam Vihar",
      "Loni",
      "Palam"
    ]
  },
  "Denver": {
    core: [
      "Denver",
      "Lodo",
      "Capitol Hill",
      "Cherry Creek",
      "Five Points",
      "Sloan's Lake",
      "Washington Park",
      "Highlands",
      "Park Hill",
      "Stapleton",
      "South Denver",
      "University Park",
      "Greenwood Village",
      "Aurora",
      "Commerce City"
    ],
    fringe: [
      "Lakewood",
      "Littleton",
      "Arvada",
      "Broomfield",
      "Wheat Ridge",
      "Thornton",
      "Englewood",
      "Golden",
      "Brighton",
      "Castle Rock",
      "Parker",
      "Northglenn",
      "Westminster",
      "Lone Tree",
      "Longmont"
    ]
  },
  "Detroit": {
    core: [
      "Detroit",
      "Midtown",
      "Downtown",
      "Greektown",
      "Corktown",
      "Rivertown",
      "Brush Park",
      "West Village",
      "East English Village",
      "Indian Village",
      "Palmer Woods",
      "Woodbridge",
      "University District",
      "Chandler Park",
      "Jefferson Chalmers"
    ],
    fringe: [
      "Southfield",
      "Dearborn",
      "Warren",
      "Royal Oak",
      "Ferndale",
      "Livonia",
      "Farmington Hills",
      "Berkley",
      "Troy",
      "Clawson",
      "Grosse Pointe",
      "Redford",
      "Westland",
      "Taylor",
      "Novi"
    ]
  },
  "Dubbo": {
    core: [
      "Dubbo",
      "Dubbo West",
      "Dubbo South",
      "Dubbo North",
      "West Dubbo",
      "East Dubbo",
      "South Dubbo",
      "North Dubbo",
      "Dubbo CBD",
      "Delroy Park",
      "Bardon Park",
      "Orana Heights",
      "Tarrabulga",
      "Ballimore",
      "Mumbil"
    ],
    fringe: [
      "Wellington",
      "Narromine",
      "Gilgandra",
      "Bogan Gate",
      "Bogan River",
      "Mendooran",
      "Dunedoo",
      "Borenore"
    ]
  },
  "Edinburgh": {
    core: [
      "Edinburgh",
      "Leith",
      "Morningside",
      "Stockbridge",
      "West End",
      "New Town",
      "Old Town",
      "Bruntsfield",
      "Meadowbank",
      "Gorgie",
      "Fountainbridge",
      "Portobello",
      "Southside",
      "Craiglockhart",
      "Colinton"
    ],
    fringe: [
      "Midlothian",
      "West Lothian",
      "Fife",
      "East Lothian",
      "Dalkeith",
      "Bonnyrigg",
      "Livingston",
      "Linlithgow",
      "Bathgate",
      "Kirkcaldy",
      "Glenrothes",
      "South Queensferry",
      "Haddington",
      "Penicuik",
      "Tranent"
    ]
  },
  "El Paso": {
    core: [
      "El Paso",
      "Downtown El Paso",
      "West El Paso",
      "Northeast El Paso",
      "East El Paso",
      "Central El Paso",
      "Mission Valley",
      "Socorro",
      "Montana Vista",
      "Sunland Park",
      "Chamizal",
      "Lower Valley",
      "Upper Valley",
      "Fabens",
      "Clint"
    ],
    fringe: [
      "Anthony",
      "Canutillo",
      "Horizon City",
      "San Elizario",
      "Fort Bliss",
      "Tornillo",
      "Vinton",
      "La Mesa",
      "Dell City",
      "Alamogordo",
      "Carlsbad",
      "Las Cruces",
      "Deming",
      "Chaparral",
      "Tucson"
    ]
  },
  "Fort Worth": {
    core: [
      "Fort Worth",
      "Downtown",
      "Tcu/westcliff",
      "Cultural District",
      "Sundance Square",
      "Southside",
      "Arlington Heights",
      "Ridglea",
      "Westworth Village",
      "Northside",
      "Eastside",
      "Fairmount",
      "Benbrook",
      "Lake Worth",
      "Saginaw"
    ],
    fringe: [
      "Burleson",
      "Crowley",
      "Watauga",
      "Haltom City",
      "North Richland Hills",
      "Southlake",
      "Keller",
      "Colleyville",
      "Grapevine",
      "Euless",
      "Bedford",
      "Mansfield",
      "Aledo",
      "Weatherford",
      "Azle"
    ]
  },
  "Geelong": {
    core: [
      "Geelong",
      "Geelong West",
      "Newtown",
      "Highton",
      "Lara",
      "Bell Park",
      "North Geelong",
      "South Geelong",
      "Corio",
      "Breakwater",
      "East Geelong",
      "Manifold Heights",
      "Whittington",
      "Leopold",
      "Grovedale"
    ],
    fringe: [
      "Bellarine",
      "Queenscliff",
      "Point Lonsdale",
      "Drysdale",
      "Barwon Heads",
      "Ocean Grove",
      "Torquay",
      "Anglesea",
      "Winchelsea",
      "Bannockburn",
      "Ceres",
      "Moolap",
      "Fyansford",
      "Little River"
    ]
  },
  "Geraldton": {
    core: [
      "Geraldton",
      "Beachlands",
      "Berkeley Vale",
      "Drummond Cove",
      "Geraldton North",
      "Geraldton South",
      "Rangeway",
      "Wonthella",
      "Spalding",
      "Mahomets Flats",
      "Mount Tarcoola",
      "Sunset Beach",
      "Little Grove",
      "Strathalbyn",
      "Riverton"
    ],
    fringe: [
      "Dongara",
      "Greenough",
      "Mullewa",
      "Nanson",
      "Yuna",
      "Pindar",
      "Walkaway",
      "Chapman Valley",
      "Binnu",
      "Nabawa",
      "Mingenew",
      "Morawa",
      "Three Springs",
      "Coorow",
      "Perenjori"
    ]
  },
  "Gold Coast": {
    core: [
      "Gold Coast",
      "Surfers Paradise",
      "Broadbeach",
      "Burleigh Heads",
      "Southport",
      "Coolangatta",
      "Robina",
      "Mermaid Beach",
      "Palm Beach",
      "Nerang",
      "Carrara",
      "Ashmore",
      "Upper Coomera",
      "Helensvale",
      "Coomera"
    ],
    fringe: [
      "Oxenford",
      "Tallebudgera",
      "Tugun",
      "Elanora",
      "Runaway Bay",
      "Labrador",
      "Arundel",
      "Pacific Pines",
      "Benowa",
      "Ormeau",
      "Pimpama",
      "Biggera Waters"
    ]
  },
  "Hervey Bay": {
    core: [
      "Hervey Bay",
      "Urangan",
      "Torquay",
      "Scarness",
      "Pialba",
      "Burrum Heads",
      "Kawungan",
      "Nikenbah",
      "Eli Waters",
      "River Heads",
      "Point Vernon",
      "Craignish",
      "Wondunna",
      "Fraser Island",
      "Hervey Bay CBD"
    ],
    fringe: [
      "Maryborough",
      "Booral",
      "Toogoom",
      "Howard",
      "Burrum River",
      "Dundowran",
      "Yengarie",
      "Tinana",
      "Mungar",
      "Pialba South",
      "Granville",
      "Boonooroo",
      "Burrum Town",
      "Kawungan South"
    ]
  },
  "Hobart": {
    core: [
      "Hobart",
      "North Hobart",
      "South Hobart",
      "West Hobart",
      "Battery Point",
      "Sandy Bay",
      "Bellerive",
      "Lutana",
      "Glenorchy",
      "Moonah",
      "Derwent Park",
      "New Town",
      "Montrose",
      "Claremont",
      "Kingston"
    ],
    fringe: [
      "Brighton",
      "Sorell",
      "Howrah",
      "Cambridge",
      "Huntingfield",
      "Margate",
      "Dunalley",
      "Bream Creek",
      "Cygnet",
      "Sandfly",
      "Seven Mile Beach",
      "Blackmans Bay",
      "South Arm",
      "Lindisfarne",
      "Clarendon Vale"
    ]
  },
  "Houston": {
    core: [
      "Houston",
      "Downtown",
      "Midtown",
      "Galleria",
      "Greenway",
      "Montrose",
      "Museum District",
      "West University",
      "Rice Village",
      "Heights",
      "Eado",
      "Spring Branch",
      "Katy",
      "Clear Lake",
      "Energy Corridor"
    ],
    fringe: [
      "Sugar Land",
      "The Woodlands",
      "Klein",
      "Cypress",
      "Pearland",
      "Friendswood",
      "League City",
      "Humble",
      "Spring",
      "Tomball",
      "Baytown",
      "Conroe",
      "Atascocita",
      "Richmond",
      "Missouri City"
    ]
  },
  "Hyderabad": {
    core: [
      "Hyderabad",
      "Banjara Hills",
      "Jubilee Hills",
      "Hitech City",
      "Gachibowli",
      "Kondapur",
      "Madhapur",
      "Secunderabad",
      "Ameerpet",
      "Somajiguda",
      "Begumpet",
      "Dilsukhnagar",
      "LB Nagar",
      "Kukatpally",
      "Malkajgiri"
    ],
    fringe: [
      "Shamshabad",
      "Sainikpuri",
      "Kompally",
      "Nagole",
      "Miyapur",
      "Nizampet",
      "Bachupally",
      "Saroornagar",
      "Medchal",
      "Uppal",
      "Hayathnagar",
      "Shadnagar",
      "Shankarpally",
      "Kothagudem"
    ]
  },
  "Indianapolis": {
    core: [
      "Indianapolis",
      "Downtown",
      "Broad Ripple",
      "Fishers",
      "Carmel",
      "Lawrence",
      "Southport",
      "Castleton",
      "Greenwood",
      "Avon",
      "Zionsville",
      "Westfield",
      "Beech Grove",
      "Noblesville",
      "Perry Township"
    ],
    fringe: [
      "Plainfield",
      "Brownsburg",
      "Greenfield",
      "Shelbyville",
      "Mooresville",
      "Franklin",
      "New Palestine",
      "Whiteland",
      "Martinsville",
      "Lebanon",
      "Danville"
    ]
  },
  "Jacksonville": {
    core: [
      "Jacksonville",
      "Downtown",
      "Southbank",
      "San Marco",
      "Riverside",
      "Avondale",
      "Mandarin",
      "Beaches",
      "Westside",
      "Arlington",
      "Ortega",
      "St. Nicholas",
      "Northside",
      "Jacksonville Beach",
      "Ponte Vedra Beach"
    ],
    fringe: [
      "Orange Park",
      "Middleburg",
      "Fleming Island",
      "Green Cove Springs",
      "St. Augustine",
      "Yulee",
      "Fernandina Beach",
      "Kingsland",
      "Nassau Village Ratliff",
      "Callahan",
      "Hastings",
      "Palatka",
      "Baldwin",
      "Clay Hill",
      "Fruit Cove"
    ]
  },
  "Jurong East": {
    core: [
      "Jurong East",
      "Jurong West",
      "Bukit Batok",
      "Bukit Panjang",
      "Tampines",
      "Bedok",
      "Punggol",
      "Sengkang",
      "Woodlands",
      "Yishun",
      "Ang Mo Kio",
      "Toa Payoh",
      "Bishan",
      "Novena",
      "Queenstown"
    ],
    fringe: [
      "Clementi",
      "Dunearn",
      "Choa Chu Kang",
      "Kranji",
      "Seletar",
      "Sembawang",
      "Paya Lebar",
      "Serangoon",
      "Hougang",
      "Pasir Ris",
      "Boon Lay",
      "Loyang",
      "East Coast",
      "Marine Parade"
    ]
  },
  "Kalgoorlie": {
    core: [
      "Kalgoorlie",
      "West Kalgoorlie",
      "South Kalgoorlie",
      "Hannans",
      "Boulder",
      "Kambalda",
      "Kalgoorlie East",
      "Kalgoorlie West",
      "Piccadilly",
      "Somerville",
      "Mckay",
      "Mount Margaret",
      "Coolgardie",
      "Kambalda West",
      "Boulder West"
    ],
    fringe: [
      "Menzies",
      "Narembeen",
      "Southern Cross",
      "Leonora",
      "Laverton",
      "Norseman",
      "Rothsay",
      "Bulldog",
      "Dundas",
      "Kookynie",
      "Widgiemooltha",
      "Boorara"
    ]
  },
  "Kwun Tong": {
    core: [
      "Kwun Tong",
      "Ngau Tau Kok",
      "Kowloon Bay",
      "Yau Tong",
      "Tseung Kwan O",
      "Choi Hung",
      "Wong Tai Sin",
      "Sham Shui Po",
      "To Kwa Wan",
      "Hung Hom",
      "Kowloon City",
      "Lam Tin",
      "Tsim Sha Tsui",
      "Jordan",
      "Mong Kok"
    ],
    fringe: [
      "Tuen Mun",
      "Tin Shui Wai",
      "Yuen Long",
      "Fanling",
      "Sheung Shui",
      "Tai Po",
      "Shatin",
      "Sai Kung",
      "Discovery Bay",
      "Lantau Island",
      "Tsuen Wan",
      "Kwai Chung",
      "Tsing Yi",
      "Cheung Sha Wan",
      "Lai Chi Kok"
    ]
  },
  "Las Vegas": {
    core: [
      "Las Vegas",
      "The Strip",
      "Downtown",
      "Summerlin",
      "Spring Valley",
      "Paradise",
      "Henderson",
      "Enterprise",
      "Southern Highlands",
      "Sahara",
      "Northeast Las Vegas",
      "East Las Vegas",
      "West Las Vegas",
      "Aliante",
      "Sunrise Manor"
    ],
    fringe: [
      "North Las Vegas",
      "Boulder City",
      "Pahrump",
      "Mesquite",
      "Laughlin",
      "Green Valley",
      "Summerlin South",
      "Mount Charleston",
      "Blue Diamond",
      "Searchlight",
      "Sandy Valley",
      "Jean",
      "Indian Springs",
      "Caliente"
    ]
  },
  "Launceston": {
    core: [
      "Launceston",
      "Kings Meadows",
      "Newstead",
      "South Launceston",
      "West Launceston",
      "East Launceston",
      "Invermay",
      "Mowbray",
      "Prospect Vale",
      "Norwood",
      "Riverside",
      "Trevallyn",
      "Waverley",
      "St Leonards",
      "Relbia"
    ],
    fringe: [
      "George Town",
      "Perth",
      "Evandale",
      "Longford",
      "Bridport",
      "Hadspen",
      "Legana",
      "Kings Park",
      "Westbury",
      "Campbell Town",
      "Swansea",
      "Bicheno",
      "Deloraine",
      "Cressy",
      "Sorell"
    ]
  },
  "London": {
    core: [
      "London",
      "Canary Wharf",
      "City Of London",
      "Southwark",
      "Islington",
      "Camden",
      "Westminster",
      "Hackney",
      "Tower Hamlets",
      "Lambeth",
      "Kensington",
      "Chelsea",
      "Hammersmith",
      "Fulham",
      "Bermondsey"
    ],
    fringe: [
      "Barking",
      "Dagenham",
      "Brent",
      "Waltham Forest",
      "Redbridge",
      "Harrow",
      "Barnet",
      "Havering",
      "Croydon",
      "Bromley",
      "Enfield",
      "Hounslow",
      "Richmond Upon Thames",
      "Sutton",
      "Kingston Upon Thames"
    ]
  },
  "Los Angeles": {
    core: [
      "Los Angeles",
      "Downtown Los Angeles",
      "Hollywood",
      "West Hollywood",
      "Beverly Hills",
      "Santa Monica",
      "Culver City",
      "Pasadena",
      "Koreatown",
      "Silver Lake",
      "Echo Park",
      "Brentwood",
      "Westwood",
      "Mid Wilshire",
      "North Hollywood"
    ],
    fringe: [
      "Burbank",
      "Glendale",
      "Torrance",
      "Inglewood",
      "Carson",
      "Hawthorne",
      "Compton",
      "South Gate",
      "Bellflower",
      "Lakewood",
      "Downey",
      "Paramount",
      "Gardena",
      "San Fernando",
      "Pico Rivera"
    ]
  },
  "Louisville": {
    core: [
      "Louisville",
      "Downtown",
      "Old Louisville",
      "Nulu",
      "Highlands",
      "East End",
      "Jeffersontown",
      "Shively",
      "St. Matthews",
      "South Louisville",
      "West Louisville",
      "Clifton",
      "Fern Creek",
      "Hurstbourne",
      "Anchorage"
    ],
    fringe: [
      "Jeffersonville",
      "Clarksville",
      "Sellersburg",
      "Prospect",
      "Shepherdsville",
      "Bardstown",
      "Elizabethtown",
      "Shelbyville",
      "Radcliff",
      "New Albany",
      "Floyds Knobs",
      "Middletown",
      "Hillview",
      "Valley Station"
    ]
  },
  "Mackay": {
    core: [
      "Mackay",
      "East Mackay",
      "West Mackay",
      "North Mackay",
      "South Mackay",
      "Mackay Harbour",
      "Slade Point",
      "Bucasia",
      "Dolphin Heads",
      "Andergrove",
      "Ooralea",
      "Paget",
      "Mackay City",
      "Walkerston",
      "Mirani"
    ],
    fringe: [
      "Sarina",
      "Finch Hatton",
      "Marian",
      "Glenella",
      "Eimeo",
      "Hay Point",
      "Shoal Point",
      "Kuttabul",
      "Balberra",
      "Dumbleton",
      "Nindaroo",
      "Mackay South",
      "Mackay North",
      "Mackay West"
    ]
  },
  "Manchester": {
    core: [
      "Manchester",
      "Salford",
      "Trafford",
      "Deansgate",
      "Northern Quarter",
      "Ancoats",
      "Chorlton",
      "Didsbury",
      "Fallowfield",
      "Whalley Range",
      "Hulme",
      "Stretford",
      "Old Trafford",
      "Gorton",
      "Levenshulme"
    ],
    fringe: [
      "Stockport",
      "Bolton",
      "Bury",
      "Rochdale",
      "Tameside",
      "Trafford Park",
      "Wigan",
      "Salford Quays",
      "Altrincham",
      "Ashton Under Lyne",
      "Cheshire",
      "Eccles",
      "Swinton",
      "Farnworth",
      "Heywood"
    ]
  },
  "Marina Bay": {
    core: [
      "Marina Bay",
      "Raffles Place",
      "Chinatown",
      "Tanjong Pagar",
      "Bugis",
      "City Hall",
      "Dhoby Ghaut",
      "Orchard",
      "Clarke Quay",
      "Little India",
      "Kampong Glam",
      "Novena",
      "Bishan",
      "Toa Payoh",
      "Queenstown"
    ],
    fringe: [
      "Tampines",
      "Bedok",
      "Punggol",
      "Sengkang",
      "Woodlands",
      "Yishun",
      "Jurong West",
      "Jurong East",
      "Bukit Batok",
      "Bukit Panjang",
      "Ang Mo Kio",
      "Hougang",
      "Serangoon",
      "Pasir Ris",
      "Loyang"
    ]
  },
  "Memphis": {
    core: [
      "Memphis",
      "Downtown",
      "Midtown",
      "East Memphis",
      "South Memphis",
      "North Memphis",
      "Whitehaven",
      "Cordova",
      "Collierville",
      "Germantown",
      "Bartlett",
      "Hickory Hill",
      "Frayser",
      "Lakeland",
      "Millington"
    ],
    fringe: [
      "Southaven",
      "Olive Branch",
      "Horn Lake",
      "West Memphis",
      "Atoka",
      "Arlington",
      "Covington",
      "Southeast Memphis"
    ]
  },
  "Mildura": {
    core: [
      "Mildura",
      "Irymple",
      "Merbein",
      "Nichols Point",
      "Red Cliffs",
      "Mildura South",
      "Mildura West",
      "Mildura East",
      "Buronga",
      "Koorlong",
      "Cowanna",
      "Pooncarie",
      "Mildura Central",
      "Mildura North",
      "Mildura Rural"
    ],
    fringe: [
      "Wentworth",
      "Wentworth Falls",
      "Ouyen",
      "Robinvale",
      "Mildura Rural City",
      "Merbein South",
      "Merbein West",
      "Red Cliffs East",
      "Irymple East",
      "Irymple West"
    ]
  },
  "Mong Kok": {
    core: [
      "Mong Kok",
      "Yau Ma Tei",
      "Prince Edward",
      "Sham Shui Po",
      "Tsim Sha Tsui",
      "Jordan",
      "Kowloon City",
      "Hung Hom",
      "To Kwa Wan",
      "Tai Kok Tsui",
      "Choi Hung",
      "Ngau Tau Kok",
      "Kowloon Bay",
      "Wong Tai Sin",
      "Chungking Mansions"
    ],
    fringe: [
      "Kwun Tong",
      "Lam Tin",
      "Tseung Kwan O",
      "Sai Kung",
      "Shatin",
      "Tai Po",
      "Fanling",
      "Sheung Shui",
      "Yuen Long",
      "Tin Shui Wai",
      "Tuen Mun",
      "Tsuen Wan",
      "Lantau Island",
      "Discovery Bay",
      "Cheung Chau"
    ]
  },
  "Montreal": {
    core: [
      "Montreal",
      "Laval",
      "Longueuil",
      "Westmount",
      "Mont Royal",
      "Outremont",
      "Saint Laurent",
      "Ahuntsic Cartierville",
      "Rosemont La Petite Patrie",
      "Villeray Saint Michel Parc Extension",
      "Plateau Mont Royal",
      "Verdun",
      "Côte Des Neiges",
      "Saint Léonard",
      "Châteauguay"
    ],
    fringe: [
      "Brossard",
      "Saint Jean Sur Richelieu",
      "Repentigny",
      "Terrebonne",
      "L'assomption",
      "Blainville",
      "Saint Eustache",
      "Sainte Thérèse",
      "Lavaltrie",
      "Mascouche",
      "Candiac",
      "Delson",
      "Carignan",
      "Saint Bruno De Montarville",
      "Joliette"
    ]
  },
  "Mount Gambier": {
    core: [
      "Mount Gambier",
      "Compton",
      "Suttontown",
      "Moorak",
      "Yahl",
      "Nangwarry",
      "Mount Gambier East",
      "Mount Gambier West",
      "Mount Gambier South",
      "Mount Gambier North",
      "Riverton",
      "Cave Gardens",
      "Blue Lake",
      "Glenburnie",
      "Woolwash"
    ],
    fringe: [
      "Millicent",
      "Penola",
      "Portland",
      "Tantanoola",
      "Kalangadoo",
      "Rendelsham",
      "Mount Schank",
      "Coonawarra",
      "Naracoorte",
      "Bordertown",
      "Apsley",
      "Robe"
    ]
  },
  "Mumbai": {
    core: [
      "Mumbai",
      "Bandra",
      "Juhu",
      "Andheri",
      "Dadar",
      "Lower Parel",
      "Fort",
      "Nariman Point",
      "Malabar Hill",
      "Worli",
      "Khar",
      "Versova",
      "Ghatkopar",
      "Thane",
      "Borivali"
    ],
    fringe: [
      "Navi Mumbai",
      "Vashi",
      "Kharghar",
      "Dombivli",
      "Ulhasnagar",
      "Mira Bhayandar",
      "Bhayandar",
      "Virar",
      "Palghar",
      "Airoli",
      "Dahisar",
      "Malad",
      "Goregaon",
      "Borivali West",
      "Kandivali"
    ]
  },
  "Nashville": {
    core: [
      "Nashville",
      "Downtown Nashville",
      "Midtown",
      "East Nashville",
      "West Nashville",
      "The Gulch",
      "Music Row",
      "Sylvan Park",
      "Green Hills",
      "Bellevue",
      "Hermitage",
      "Donelson",
      "Brentwood",
      "Inglewood",
      "Old Hickory"
    ],
    fringe: [
      "Franklin",
      "Murfreesboro",
      "Hendersonville",
      "Gallatin",
      "Smyrna",
      "La Vergne",
      "Mount Juliet",
      "Lebanon",
      "Spring Hill",
      "Goodlettsville",
      "Nolensville",
      "White House",
      "Ashland City",
      "Thompson's Station",
      "Portland"
    ]
  },
  "New York": {
    core: [
      "New York",
      "Manhattan",
      "Brooklyn",
      "Queens",
      "Bronx",
      "Staten Island",
      "Harlem",
      "East Village",
      "West Village",
      "Upper East Side",
      "Upper West Side",
      "Soho",
      "Chelsea",
      "Financial District",
      "Midtown"
    ],
    fringe: [
      "Jersey City",
      "Hoboken",
      "Long Island City",
      "Astoria",
      "Williamsburg",
      "Bushwick",
      "Park Slope",
      "Bay Ridge",
      "Riverdale",
      "Flushing",
      "Elmhurst",
      "Forest Hills",
      "South Bronx",
      "Greenpoint"
    ]
  },
  "Newcastle": {
    core: [
      "Newcastle",
      "Merewether",
      "Hamilton",
      "Cooks Hill",
      "Bar Beach",
      "The Junction",
      "Waratah",
      "Mayfield",
      "Kotara",
      "Birmingham Gardens",
      "Broadmeadow",
      "Lambton",
      "Wickham",
      "Islington",
      "Carrington"
    ],
    fringe: [
      "Charlestown",
      "Lake Macquarie",
      "Warners Bay",
      "Cardiff",
      "Belmont",
      "Toronto",
      "Wallsend",
      "Minmi",
      "Adamstown Heights",
      "New Lambton",
      "Fletcher",
      "Dudley",
      "Kahibah",
      "Shortland",
      "North Lambton"
    ]
  },
  "North Point": {
    core: [
      "North Point",
      "Fortress Hill",
      "Quarry Bay",
      "Tai Koo",
      "Shau Kei Wan",
      "Chai Wan",
      "Causeway Bay",
      "Wanchai",
      "Admiralty",
      "Central",
      "Sheung Wan",
      "Sai Ying Pun",
      "Mid Levels",
      "Happy Valley",
      "Tin Hau"
    ],
    fringe: [
      "Kowloon Bay",
      "Kwun Tong",
      "Tseung Kwan O",
      "Yau Tong",
      "Choi Hung",
      "Wong Tai Sin",
      "Shatin",
      "Tai Po",
      "Fanling",
      "Sheung Shui",
      "Yuen Long",
      "Tin Shui Wai",
      "Tuen Mun",
      "Tsuen Wan",
      "Discovery Bay"
    ]
  },
  "Nowra": {
    core: [
      "Nowra",
      "Bomaderry",
      "North Nowra",
      "South Nowra",
      "Nowra CBD",
      "Worrigee",
      "Bodalla",
      "Terara",
      "Jaspers Brush",
      "Shoalhaven Heads",
      "East Nowra",
      "West Nowra",
      "Pyree",
      "Meroo Meadow",
      "Culburra Beach"
    ],
    fringe: [
      "Ulladulla",
      "Milton",
      "Berry",
      "Huskisson",
      "Vincentia",
      "Sanctuary Point",
      "St Georges Basin",
      "Greenwell Point",
      "Bawley Point",
      "Kangaroo Valley",
      "Sussex Inlet",
      "Wollongong",
      "Gerringong",
      "Kiama",
      "Dapto"
    ]
  },
  "Oklahoma City": {
    core: [
      "Oklahoma City",
      "Bricktown",
      "Downtown",
      "Midtown",
      "Plaza District",
      "Automobile Alley",
      "Capitol Hill",
      "Heritage Hills",
      "Crestview",
      "Mesta Park",
      "Edgemere Park",
      "The Village",
      "Nichols Hills",
      "Putnam City",
      "Warr Acres"
    ],
    fringe: [
      "Norman",
      "Edmond",
      "Moore",
      "Midwest City",
      "Del City",
      "Yukon",
      "Mustang",
      "Choctaw",
      "Harrah",
      "El Reno",
      "Blanchard",
      "Newcastle",
      "Tuttle",
      "Luther",
      "Guthrie"
    ]
  },
  "Orange": {
    core: [
      "Orange",
      "Borenore",
      "Spring Hill",
      "Canobolas",
      "Mount Canobolas",
      "Lidster",
      "Mullion Creek",
      "Cliefden",
      "Orange CBD",
      "Duntryleague",
      "Cudal",
      "Orange East"
    ],
    fringe: [
      "Molong",
      "Blayney",
      "Cabonne",
      "Manildra"
    ]
  },
  "Orchard": {
    core: [
      "Orchard",
      "Somerset",
      "Dhoby Ghaut",
      "Bencoolen",
      "River Valley",
      "Novena",
      "Little India",
      "Rochor",
      "Killiney",
      "Emerald Hill",
      "Tanglin",
      "Fort Canning",
      "Bishan",
      "Toa Payoh",
      "Newton"
    ],
    fringe: [
      "Bugis",
      "Kallang",
      "Geylang",
      "Balestier",
      "Thomson",
      "Queenstown",
      "Tiong Bahru",
      "Holland Village",
      "Bukit Timah",
      "Serangoon",
      "Paya Lebar",
      "Bedok",
      "Pasir Ris",
      "Sengkang",
      "Yishun"
    ]
  },
  "Paris": {
    core: [
      "Paris",
      "La Défense",
      "Saint Denis",
      "Montreuil",
      "Neuilly Sur Seine",
      "Boulogne Billancourt",
      "Levallois Perret",
      "Issy Les Moulineaux",
      "Pantin",
      "Aubervilliers",
      "Nanterre",
      "Vitry Sur Seine",
      "Clichy",
      "Malakoff",
      "Suresnes"
    ],
    fringe: [
      "Saint Ouen",
      "Argenteuil",
      "Colombes",
      "Courbevoie",
      "Gennevilliers",
      "Asnières Sur Seine",
      "Bobigny",
      "Sevran",
      "Drancy",
      "Noisy Le Sec",
      "Bagneux",
      "Clamart",
      "Châtillon",
      "Rueil Malmaison"
    ]
  },
  "Philadelphia": {
    core: [
      "Philadelphia",
      "Center City",
      "University City",
      "Old City",
      "South Philadelphia",
      "West Philadelphia",
      "Northeast Philadelphia",
      "Fishtown",
      "Northern Liberties",
      "Manayunk",
      "Rittenhouse",
      "Queen Village",
      "Chestnut Hill",
      "Mount Airy",
      "East Falls"
    ],
    fringe: [
      "Camden",
      "Burlington",
      "Conshohocken",
      "West Chester",
      "Lansdale",
      "Norristown",
      "Upper Darby",
      "Haverford",
      "Radnor",
      "Bensalem",
      "Langhorne",
      "Levittown",
      "Willow Grove",
      "Hatboro",
      "Yardley"
    ]
  },
  "Phoenix": {
    core: [
      "Phoenix",
      "Downtown",
      "Tempe",
      "Scottsdale",
      "Chandler",
      "Glendale",
      "Mesa",
      "South Mountain",
      "Ahwatukee",
      "North Mountain",
      "Encanto",
      "Desert Ridge",
      "Laveen",
      "Arcadia",
      "Estrella"
    ],
    fringe: [
      "Gilbert",
      "Peoria",
      "Goodyear",
      "Avondale",
      "Surprise",
      "Queen Creek",
      "Buckeye",
      "Cave Creek",
      "Fountain Hills",
      "Sun City",
      "Tolleson",
      "Maricopa",
      "Chandler Heights",
      "Litchfield Park",
      "San Tan Valley"
    ]
  },
  "Port Macquarie": {
    core: [
      "Port Macquarie",
      "Lake Cathie",
      "Wauchope",
      "Thrumster",
      "Hastings",
      "Bonny Hills",
      "Lighthouse Beach",
      "Shelly Beach",
      "Flynns Beach",
      "North Haven",
      "Queens Lake",
      "Port Macquarie CBD",
      "Kew",
      "Lorne",
      "Sancrox"
    ],
    fringe: [
      "Crescent Head",
      "South West Rocks",
      "Bago",
      "Hastings Point",
      "Coffs Harbour"
    ]
  },
  "Portland": {
    core: [
      "Portland",
      "Downtown",
      "Pearl District",
      "Old Town",
      "South Waterfront",
      "Northwest District",
      "Alberta Arts District",
      "Hawthorne",
      "Sellwood",
      "Lloyd District",
      "Eastside",
      "Kerns",
      "Buckman",
      "Irvington",
      "Laurelhurst"
    ],
    fringe: [
      "Beaverton",
      "Gresham",
      "Tigard",
      "Lake Oswego",
      "Milwaukie",
      "Happy Valley",
      "West Linn",
      "Clackamas",
      "Oregon City",
      "Fairview",
      "Troutdale",
      "Wood Village",
      "Wilsonville",
      "Sherwood",
      "Canby"
    ]
  },
  "Punggol": {
    core: [
      "Punggol",
      "Punggol Central",
      "Punggol East",
      "Punggol West",
      "Punggol South",
      "Punggol Waterway",
      "Punggol Town Centre",
      "Punggol Digital District",
      "Punggol Point",
      "Punggol Marina",
      "Punggol Walk",
      "Punggol Drive",
      "Punggol Place",
      "Punggol Field",
      "Punggol Beach"
    ],
    fringe: [
      "Sengkang",
      "Woodlands",
      "Serangoon",
      "Kovan",
      "Hougang",
      "Pasir Ris",
      "Tampines",
      "Bedok",
      "Yishun",
      "Ang Mo Kio",
      "Bishan",
      "Jurong East",
      "Jurong West",
      "Bukit Batok",
      "Choa Chu Kang"
    ]
  },
  "Quarry Bay": {
    core: [
      "Quarry Bay",
      "Tai Koo",
      "North Point",
      "Chai Wan",
      "Shau Kei Wan",
      "Causeway Bay",
      "Wanchai",
      "Admiralty",
      "Central",
      "Sheung Wan",
      "Sai Ying Pun",
      "Fortress Hill",
      "Mid Levels",
      "Happy Valley",
      "Tin Hau"
    ],
    fringe: [
      "Kowloon Bay",
      "Kwun Tong",
      "Tseung Kwan O",
      "Yau Tong",
      "Choi Hung",
      "Wong Tai Sin",
      "Shatin",
      "Tai Po",
      "Fanling",
      "Sheung Shui",
      "Yuen Long",
      "Tin Shui Wai",
      "Tuen Mun",
      "Tsuen Wan",
      "Discovery Bay"
    ]
  },
  "Raffles Place": {
    core: [
      "Raffles Place",
      "Marina Bay",
      "Chinatown",
      "Tanjong Pagar",
      "Bugis",
      "City Hall",
      "Dhoby Ghaut",
      "Orchard",
      "Clarke Quay",
      "Little India",
      "Kampong Glam",
      "Novena",
      "Bishan",
      "Toa Payoh",
      "Queenstown"
    ],
    fringe: [
      "Tampines",
      "Bedok",
      "Punggol",
      "Sengkang",
      "Woodlands",
      "Yishun",
      "Jurong West",
      "Jurong East",
      "Bukit Batok",
      "Bukit Panjang",
      "Ang Mo Kio",
      "Hougang",
      "Serangoon",
      "Pasir Ris",
      "Loyang"
    ]
  },
  "Rockhampton": {
    core: [
      "Rockhampton",
      "North Rockhampton",
      "South Rockhampton",
      "West Rockhampton",
      "Parkhurst",
      "Gracemere",
      "Mount Morgan",
      "Kawana",
      "Frenchville",
      "The Range",
      "Berserker",
      "Norman Gardens",
      "Rockyview",
      "Alton Downs",
      "Wandal"
    ],
    fringe: [
      "Yeppoon",
      "Emu Park",
      "Mount Archer",
      "Cawarral",
      "Zilzie",
      "Bouldercombe",
      "Nankin",
      "Marmor",
      "Rockhampton City",
      "Glenlee",
      "Nikenbah",
      "Nambour",
      "Biloela",
      "Capricorn Coast",
      "Coonarr"
    ]
  },
  "San Antonio": {
    core: [
      "San Antonio",
      "Downtown",
      "Alamo Heights",
      "Stone Oak",
      "The Dominion",
      "Tobin Hill",
      "Southtown",
      "Terrell Hills",
      "Olmos Park",
      "Castle Hills",
      "Leon Valley",
      "Medical Center",
      "Westover Hills",
      "Northwest Side",
      "East Side"
    ],
    fringe: [
      "New Braunfels",
      "Schertz",
      "Cibolo",
      "Live Oak",
      "Universal City",
      "Boerne",
      "Selma",
      "Seguin",
      "Helotes",
      "Floresville",
      "Castroville",
      "Garden Ridge",
      "Poteet",
      "San Marcos",
      "Bulverde"
    ]
  },
  "San Diego": {
    core: [
      "San Diego",
      "Downtown",
      "Little Italy",
      "Gaslamp Quarter",
      "Mission Valley",
      "Hillcrest",
      "North Park",
      "Pacific Beach",
      "La Jolla",
      "Point Loma",
      "Kearny Mesa",
      "University City",
      "Chula Vista",
      "Sorrento Valley",
      "Miramar"
    ],
    fringe: [
      "Coronado",
      "El Cajon",
      "La Mesa",
      "National City",
      "Poway",
      "Escondido",
      "San Marcos",
      "Vista",
      "Carlsbad",
      "Oceanside",
      "Encinitas",
      "Solana Beach",
      "Ramona",
      "Fallbrook",
      "Lemon Grove"
    ]
  },
  "San Francisco": {
    core: [
      "San Francisco",
      "Financial District",
      "Soma",
      "Mission District",
      "Nob Hill",
      "North Beach",
      "Tenderloin",
      "Chinatown",
      "Pacific Heights",
      "Haight Ashbury",
      "Castro",
      "Excelsior",
      "Bayview Hunters Point",
      "Sunset District",
      "Richmond District"
    ],
    fringe: [
      "Daly City",
      "South San Francisco",
      "Brisbane",
      "Pacifica",
      "Millbrae",
      "Burlingame",
      "San Bruno",
      "San Mateo",
      "Foster City",
      "Belmont",
      "Redwood City",
      "Menlo Park",
      "Palo Alto",
      "Mountain View",
      "Hayward"
    ]
  },
  "San Jose": {
    core: [
      "San Jose",
      "Downtown San Jose",
      "Santana Row",
      "Willow Glen",
      "Almaden Valley",
      "Evergreen",
      "North San Jose",
      "South San Jose",
      "Rose Garden",
      "Berryessa",
      "Cambrian Park",
      "East San Jose",
      "West San Jose",
      "Japantown",
      "Silver Creek"
    ],
    fringe: [
      "Santa Clara",
      "Milpitas",
      "Sunnyvale",
      "Cupertino",
      "Mountain View",
      "Los Gatos",
      "Morgan Hill",
      "Gilroy",
      "Palo Alto",
      "Fremont",
      "Saratoga",
      "Campbell",
      "Los Altos",
      "Menlo Park",
      "Redwood City"
    ]
  },
  "Seattle": {
    core: [
      "Seattle",
      "Capitol Hill",
      "Ballard",
      "South Lake Union",
      "West Seattle",
      "University District",
      "Pioneer Square",
      "Belltown",
      "Northgate",
      "South Seattle",
      "Magnolia",
      "Beacon Hill",
      "Greenwood",
      "Westwood",
      "Rainier Valley"
    ],
    fringe: [
      "Bellevue",
      "Redmond",
      "Kirkland",
      "Renton",
      "Tukwila",
      "Shoreline",
      "Bothell",
      "Issaquah",
      "Mercer Island",
      "Lynnwood",
      "Everett",
      "Mill Creek",
      "Maple Valley",
      "Burien",
      "Des Moines"
    ]
  },
  "Sengkang": {
    core: [
      "Sengkang",
      "Sengkang East",
      "Sengkang West",
      "Sengkang Central",
      "Sengkang South",
      "Rivervale",
      "Compassvale",
      "Fernvale",
      "Anchorvale",
      "Buangkok",
      "Punggol",
      "Seletar",
      "Sengkang Industrial Park",
      "Sengkang Square",
      "Sengkang Riverside"
    ],
    fringe: [
      "Hougang",
      "Serangoon",
      "Kovan",
      "Bishan",
      "Yishun",
      "Woodlands",
      "Tampines",
      "Pasir Ris",
      "Bedok",
      "Ang Mo Kio",
      "Boon Lay",
      "Jurong East",
      "Jurong West",
      "Bukit Panjang"
    ]
  },
  "Sentosa": {
    core: [
      "Sentosa",
      "Harbourfront",
      "Vivocity",
      "Tanjong Pagar",
      "Marina Bay",
      "Raffles Place",
      "Orchard",
      "Clarke Quay",
      "Chinatown",
      "Bugis",
      "Little India",
      "Dhoby Ghaut",
      "City Hall",
      "Novena",
      "Queenstown"
    ],
    fringe: [
      "Tampines",
      "Bedok",
      "Punggol",
      "Sengkang",
      "Woodlands",
      "Yishun",
      "Jurong West",
      "Jurong East",
      "Bukit Batok",
      "Bukit Panjang",
      "Ang Mo Kio",
      "Hougang",
      "Serangoon",
      "Pasir Ris",
      "Loyang"
    ]
  },
  "Shepparton": {
    core: [
      "Shepparton",
      "Kialla",
      "Mooroopna",
      "Tatura",
      "Dookie",
      "Grahamvale",
      "Goulburn Valley",
      "Lemnos",
      "Toolamba",
      "Shepparton East",
      "Shepparton North",
      "Violet Town",
      "Numurkah",
      "Merrigum",
      "Mooroopna East"
    ],
    fringe: [
      "Tatura East",
      "Dookie South",
      "Mooroopna West",
      "Kialla West",
      "Grahamvale East",
      "Berrigan",
      "Cobram",
      "Rushworth",
      "Nagambie",
      "Strathmerton",
      "Yarrawonga",
      "Benalla",
      "Rochester",
      "Echuca",
      "Kyabram"
    ]
  },
  "Sunshine Coast": {
    core: [
      "Sunshine Coast",
      "Maroochydore",
      "Mooloolaba",
      "Caloundra",
      "Noosa Heads",
      "Nambour",
      "Buderim",
      "Sippy Downs",
      "Kawana Waters",
      "Coolum Beach",
      "Palmview",
      "Bli Bli",
      "Yandina",
      "Tewantin",
      "Mountain Creek"
    ],
    fringe: [
      "Beerwah",
      "Landsborough",
      "Glass House Mountains",
      "Eumundi",
      "Woombye",
      "Maleny",
      "Montville",
      "Kuluin",
      "Cotton Tree",
      "Twin Waters",
      "Buddina",
      "Dicky Beach"
    ]
  },
  "Tai Po": {
    core: [
      "Tai Po",
      "Tai Po Market",
      "Tai Wo",
      "Fanling",
      "Sha Tin",
      "Ma On Shan",
      "Wu Kai Sha",
      "Tai Po Kau",
      "Lam Tsuen",
      "Kau Lung Hang",
      "Fung Yuen",
      "Tai Po Industrial Estate",
      "Yuen Chau Tsai",
      "Pak Shek Kok",
      "Shek Wu Hui"
    ],
    fringe: [
      "North District",
      "Tseung Kwan O",
      "Sai Kung",
      "Shatin",
      "Yuen Long",
      "Tin Shui Wai",
      "Tuen Mun",
      "Kowloon",
      "Tsuen Wan",
      "Lantau Island",
      "Discovery Bay",
      "Cheung Chau",
      "Peng Chau",
      "Lamma Island",
      "Tsing Yi"
    ]
  },
  "Tampines": {
    core: [
      "Tampines",
      "Tampines North",
      "Tampines East",
      "Tampines West",
      "Tampines Central",
      "Tampines Avenue 1",
      "Tampines Avenue 10",
      "Tampines Avenue 5",
      "Tampines Industrial Park",
      "Tampines Mart",
      "Tampines Hub",
      "Tampines North Drive",
      "Tampines Street 21",
      "Tampines Street 23",
      "Tampines Street 24"
    ],
    fringe: [
      "Pasir Ris",
      "Simei",
      "Bedok",
      "Changi",
      "Paya Lebar",
      "Bishan",
      "Kallang",
      "Serangoon",
      "Hougang",
      "Ang Mo Kio",
      "Yishun",
      "Woodlands",
      "Sengkang",
      "Punggol",
      "Bedok Reservoir"
    ]
  },
  "Tamworth": {
    core: [
      "Tamworth",
      "West Tamworth",
      "East Tamworth",
      "South Tamworth",
      "North Tamworth",
      "Taminda",
      "Hillvue",
      "Kootingal",
      "Goonoo Goonoo",
      "Duri",
      "Moore Creek",
      "Winton",
      "Bobby's Plains",
      "Kingswood",
      "Oxley Vale"
    ],
    fringe: [
      "Manilla",
      "Nundle",
      "Werris Creek",
      "Gunnedah",
      "Quirindi",
      "Barraba",
      "Tamworth Regional",
      "Boggabri",
      "Merriwa",
      "Scone",
      "Weabonga"
    ]
  },
  "Toowoomba": {
    core: [
      "Toowoomba",
      "East Toowoomba",
      "South Toowoomba",
      "North Toowoomba",
      "West Toowoomba",
      "Centenary Heights",
      "Kearneys Spring",
      "Harlaxton",
      "Glenvale",
      "Wilsonton",
      "Mount Lofty",
      "Toowoomba City",
      "Rangeville",
      "Southtown",
      "Newtown"
    ],
    fringe: [
      "Highfields",
      "Meringandan",
      "Cotswold Hills",
      "Harristown",
      "Gowrie Junction",
      "Oakey",
      "Drayton",
      "Westbrook",
      "Cambooya",
      "Greenmount",
      "Pittsworth",
      "Kingsthorpe",
      "Vale View",
      "Ravensbourne",
      "Wyreema"
    ]
  },
  "Toronto": {
    core: [
      "Toronto",
      "Mississauga",
      "Markham",
      "Vaughan",
      "Scarborough",
      "North York",
      "Etobicoke",
      "York",
      "East York",
      "Downtown Toronto",
      "Richmond Hill",
      "Oakville",
      "Brampton",
      "Pickering",
      "Ajax"
    ],
    fringe: [
      "Whitby",
      "Milton",
      "Burlington",
      "Newmarket",
      "Aurora",
      "King City",
      "Maple",
      "Thornhill",
      "Woodbridge",
      "Guelph",
      "Kitchener",
      "Cambridge",
      "Oshawa",
      "Halton Hills"
    ]
  },
  "Townsville": {
    core: [
      "Townsville",
      "North Ward",
      "South Townsville",
      "West End",
      "Aitkenvale",
      "Kirwan",
      "Thuringowa Central",
      "Bohle Plains",
      "Mount Louisa",
      "Gulliver",
      "Heatley",
      "Oonoonba",
      "Pallarenda",
      "Rasmussen",
      "Rowes Bay"
    ],
    fringe: [
      "Bushland Beach",
      "Deeragun",
      "Jensen",
      "Mount St John",
      "Nelly Bay",
      "Pimlico",
      "Riverside Gardens",
      "Shaw",
      "Stuart",
      "Town Of 1770",
      "Annandale",
      "Burdekin",
      "Cluden",
      "Cranbrook",
      "Douglas"
    ]
  },
  "Tsim Sha Tsui": {
    core: [
      "Tsim Sha Tsui",
      "East Tsim Sha Tsui",
      "Jordan",
      "Yau Ma Tei",
      "Mong Kok",
      "Central",
      "Admiralty",
      "Wan Chai",
      "Causeway Bay",
      "Sheung Wan",
      "Soho",
      "Mid Levels",
      "North Point",
      "Tin Hau",
      "Quarry Bay"
    ],
    fringe: [
      "Kowloon Bay",
      "Ngau Tau Kok",
      "Lam Tin",
      "Yau Tong",
      "Tseung Kwan O",
      "Tsing Yi",
      "Tsuen Wan",
      "Sha Tin",
      "Fanling",
      "Tai Po",
      "Discovery Bay",
      "Aberdeen",
      "Wong Chuk Hang",
      "Sai Wan Ho",
      "Chai Wan"
    ]
  },
  "Tuen Mun": {
    core: [
      "Tuen Mun",
      "Tuen Mun Town Centre",
      "Sam Shing",
      "Castle Peak Bay",
      "Yam O",
      "Butterfly Estate",
      "Tsing Lung Tau",
      "Lung Mun Oasis",
      "Tin Shui Wai",
      "Yuen Long",
      "Shui Pin Wai",
      "Pui O",
      "Tuen Mun Industrial Area",
      "Kau Wa Keng",
      "Lai King"
    ],
    fringe: [
      "North District",
      "Sai Kung",
      "Kowloon",
      "Tsuen Wan",
      "Lantau Island",
      "Discovery Bay",
      "Cheung Chau",
      "Peng Chau",
      "Lamma Island",
      "Tsing Yi",
      "Shatin",
      "Tai Po",
      "Fanling"
    ]
  },
  "Vancouver": {
    core: [
      "Vancouver",
      "Burnaby",
      "Richmond",
      "West Vancouver",
      "North Vancouver",
      "Surrey",
      "Langley",
      "Delta",
      "Coquitlam",
      "Port Moody",
      "New Westminster",
      "Maple Ridge",
      "White Rock",
      "Tsawwassen",
      "Pitt Meadows"
    ],
    fringe: [
      "Abbotsford",
      "Chilliwack",
      "Mission",
      "Ladner",
      "South Surrey",
      "Langley Township",
      "Port Coquitlam",
      "Anmore",
      "Belcarra",
      "Sooke",
      "Nanaimo",
      "Duncan",
      "Parksville",
      "Qualicum Beach"
    ]
  },
  "Wagga Wagga": {
    core: [
      "Wagga Wagga",
      "Turvey Park",
      "Kooringal",
      "Bourkelands",
      "Lloyd",
      "Estella",
      "Mount Austin",
      "North Wagga Wagga",
      "South Wagga Wagga",
      "Wagga Wagga CBD",
      "Lake Albert",
      "Tatton",
      "Bomen",
      "Wagga Wagga Airport",
      "Glenfield Park"
    ],
    fringe: [
      "Mangoplah",
      "Oura",
      "Tarcutta",
      "Coolamon",
      "Junee",
      "Lockhart",
      "Narrandera",
      "Henty",
      "Bourke",
      "Barmedman",
      "Wagga Wagga Rural",
      "Merriwagga",
      "Bidgeemia"
    ]
  },
  "Wan Chai": {
    core: [
      "Wan Chai",
      "Admiralty",
      "Central",
      "Causeway Bay",
      "Happy Valley",
      "Sheung Wan",
      "Tsim Sha Tsui",
      "Mong Kok",
      "Yau Ma Tei",
      "Jordan",
      "Soho",
      "Mid Levels",
      "North Point",
      "Tin Hau",
      "Chai Wan"
    ],
    fringe: [
      "Quarry Bay",
      "Sai Wan Ho",
      "Aberdeen",
      "Wong Chuk Hang",
      "Kowloon Bay",
      "Ngau Tau Kok",
      "Lam Tin",
      "Yau Tong",
      "Tseung Kwan O",
      "Tsing Yi",
      "Tsuen Wan",
      "Sha Tin",
      "Fanling",
      "Tai Po",
      "Discovery Bay"
    ]
  },
  "Warrnambool": {
    core: [
      "Warrnambool",
      "Dennington",
      "Allansford",
      "Woodford",
      "Warrnambool CBD",
      "Koroit",
      "Purnim",
      "Logans Beach",
      "Merrivale",
      "Brierly",
      "Warrnambool East",
      "Warrnambool West",
      "Warrnambool North",
      "Warrnambool South",
      "Warrnambool Central"
    ],
    fringe: [
      "Port Fairy",
      "Bushfield",
      "Tower Hill",
      "Gnotuk",
      "Macarthur",
      "Hawkesdale",
      "Illowa",
      "Wangoom",
      "Caramut"
    ]
  },
  "Washington DC": {
    core: [
      "Washington DC",
      "Dupont Circle",
      "Georgetown",
      "Capitol Hill",
      "Foggy Bottom",
      "Adams Morgan",
      "Logan Circle",
      "West End",
      "Shaw",
      "Navy Yard",
      "Columbia Heights",
      "U Street Corridor",
      "Eastern Market",
      "Tenleytown",
      "Anacostia"
    ],
    fringe: [
      "Arlington",
      "Alexandria",
      "Silver Spring",
      "Bethesda",
      "Hyattsville",
      "Falls Church",
      "Rockville",
      "Vienna",
      "Mclean",
      "Landover",
      "Greenbelt",
      "Laurel",
      "Bowie",
      "Germantown",
      "Woodbridge"
    ]
  },
  "Wollongong": {
    core: [
      "Wollongong",
      "North Wollongong",
      "West Wollongong",
      "Towradgi",
      "Fairy Meadow",
      "Bulli",
      "Thirroul",
      "Woonona",
      "Corrimal",
      "Keiraville",
      "Mount Pleasant",
      "Mangerton",
      "Dapto",
      "Unanderra",
      "Figtree"
    ],
    fringe: [
      "Shellharbour",
      "Albion Park",
      "Warilla",
      "Oak Flats",
      "Flinders",
      "Berkeley",
      "Port Kembla",
      "Coniston",
      "Barden Ridge",
      "Kembla Grange",
      "Horsley",
      "Bellambi",
      "Scarborough"
    ]
  },
  "Woodlands": {
    core: [
      "Woodlands",
      "Woodlands North",
      "Woodlands South",
      "Woodlands East",
      "Woodlands Industrial Park",
      "Woodlands Drive",
      "Woodlands Avenue 1",
      "Woodlands Avenue 2",
      "Woodlands Avenue 3",
      "Woodlands Street 81",
      "Woodlands Street 82",
      "Woodlands Street 83",
      "Woodlands Street 84",
      "Woodlands Street 85",
      "Woodlands Street 86"
    ],
    fringe: [
      "Sembawang",
      "Yishun",
      "Sengkang",
      "Punggol",
      "Marsiling",
      "Kranji",
      "Lim Chu Kang",
      "Mandai",
      "Woodlands Waterfront",
      "Woodlands Checkpoint",
      "Seletar",
      "Punggol Point",
      "Sengkang West",
      "Bukit Batok",
      "Choa Chu Kang"
    ]
  }
};
